// pkg/proto/telegram/telegram.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: telegram/telegram.proto

package telegram

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CAUGHT: the real-send lock is closed (not production) — the message went to
// the catcher chat or only to the log; the crew's group did not get it.
type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_SENT                        DeliveryStatus = 1
	DeliveryStatus_FAILED                      DeliveryStatus = 2
	DeliveryStatus_NO_GROUP                    DeliveryStatus = 3
	DeliveryStatus_CAUGHT                      DeliveryStatus = 4
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "SENT",
		2: "FAILED",
		3: "NO_GROUP",
		4: "CAUGHT",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"SENT":                        1,
		"FAILED":                      2,
		"NO_GROUP":                    3,
		"CAUGHT":                      4,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_telegram_telegram_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_telegram_telegram_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_telegram_telegram_proto_rawDescGZIP(), []int{0}
}

type SendToCrewRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompanyId      string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	CrewId         string                 `protobuf:"bytes,2,opt,name=crew_id,json=crewId,proto3" json:"crew_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	ParseMode      string                 `protobuf:"bytes,5,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"` // "HTML" or empty
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendToCrewRequest) Reset() {
	*x = SendToCrewRequest{}
	mi := &file_telegram_telegram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToCrewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToCrewRequest) ProtoMessage() {}

func (x *SendToCrewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_telegram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToCrewRequest.ProtoReflect.Descriptor instead.
func (*SendToCrewRequest) Descriptor() ([]byte, []int) {
	return file_telegram_telegram_proto_rawDescGZIP(), []int{0}
}

func (x *SendToCrewRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *SendToCrewRequest) GetCrewId() string {
	if x != nil {
		return x.CrewId
	}
	return ""
}

func (x *SendToCrewRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendToCrewRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendToCrewRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

type EditMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompanyId      string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	ParseMode      string                 `protobuf:"bytes,5,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_telegram_telegram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_telegram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_telegram_telegram_proto_rawDescGZIP(), []int{1}
}

func (x *EditMessageRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *EditMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditMessageRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EditMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EditMessageRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

type ReplyNoteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CompanyId      string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	ParseMode      string                 `protobuf:"bytes,5,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplyNoteRequest) Reset() {
	*x = ReplyNoteRequest{}
	mi := &file_telegram_telegram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyNoteRequest) ProtoMessage() {}

func (x *ReplyNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_telegram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyNoteRequest.ProtoReflect.Descriptor instead.
func (*ReplyNoteRequest) Descriptor() ([]byte, []int) {
	return file_telegram_telegram_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyNoteRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ReplyNoteRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReplyNoteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReplyNoteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReplyNoteRequest) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

type SendResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessageId         string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // tms-telegram message id (uuid)
	Status            DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=telegram.DeliveryStatus" json:"status,omitempty"`
	ChatId            int64                  `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	TelegramMessageId int64                  `protobuf:"varint,4,opt,name=telegram_message_id,json=telegramMessageId,proto3" json:"telegram_message_id,omitempty"`
	FailureReason     string                 `protobuf:"bytes,5,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"` // Telegram's description, verbatim
	ChatTitle         string                 `protobuf:"bytes,6,opt,name=chat_title,json=chatTitle,proto3" json:"chat_title,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendResult) Reset() {
	*x = SendResult{}
	mi := &file_telegram_telegram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResult) ProtoMessage() {}

func (x *SendResult) ProtoReflect() protoreflect.Message {
	mi := &file_telegram_telegram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResult.ProtoReflect.Descriptor instead.
func (*SendResult) Descriptor() ([]byte, []int) {
	return file_telegram_telegram_proto_rawDescGZIP(), []int{3}
}

func (x *SendResult) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendResult) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *SendResult) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendResult) GetTelegramMessageId() int64 {
	if x != nil {
		return x.TelegramMessageId
	}
	return 0
}

func (x *SendResult) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *SendResult) GetChatTitle() string {
	if x != nil {
		return x.ChatTitle
	}
	return ""
}

var File_telegram_telegram_proto protoreflect.FileDescriptor

const file_telegram_telegram_proto_rawDesc = "" +
	"\n" +
	"\x17telegram/telegram.proto\x12\btelegram\"\xa7\x01\n" +
	"\x11SendToCrewRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x17\n" +
	"\acrew_id\x18\x02 \x01(\tR\x06crewId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x05 \x01(\tR\tparseMode\"\xae\x01\n" +
	"\x12EditMessageRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x05 \x01(\tR\tparseMode\"\xac\x01\n" +
	"\x10ReplyNoteRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x05 \x01(\tR\tparseMode\"\xec\x01\n" +
	"\n" +
	"SendResult\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.telegram.DeliveryStatusR\x06status\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x03R\x06chatId\x12.\n" +
	"\x13telegram_message_id\x18\x04 \x01(\x03R\x11telegramMessageId\x12%\n" +
	"\x0efailure_reason\x18\x05 \x01(\tR\rfailureReason\x12\x1d\n" +
	"\n" +
	"chat_title\x18\x06 \x01(\tR\tchatTitle*a\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SENT\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\f\n" +
	"\bNO_GROUP\x10\x03\x12\n" +
	"\n" +
	"\x06CAUGHT\x10\x042\xd4\x01\n" +
	"\x0fTelegramService\x12?\n" +
	"\n" +
	"SendToCrew\x12\x1b.telegram.SendToCrewRequest\x1a\x14.telegram.SendResult\x12A\n" +
	"\vEditMessage\x12\x1c.telegram.EditMessageRequest\x1a\x14.telegram.SendResult\x12=\n" +
	"\tReplyNote\x12\x1a.telegram.ReplyNoteRequest\x1a\x14.telegram.SendResultB.Z,github.com/TMS360/backend-pkg/proto/telegramb\x06proto3"

var (
	file_telegram_telegram_proto_rawDescOnce sync.Once
	file_telegram_telegram_proto_rawDescData []byte
)

func file_telegram_telegram_proto_rawDescGZIP() []byte {
	file_telegram_telegram_proto_rawDescOnce.Do(func() {
		file_telegram_telegram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telegram_telegram_proto_rawDesc), len(file_telegram_telegram_proto_rawDesc)))
	})
	return file_telegram_telegram_proto_rawDescData
}

var file_telegram_telegram_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telegram_telegram_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_telegram_telegram_proto_goTypes = []any{
	(DeliveryStatus)(0),        // 0: telegram.DeliveryStatus
	(*SendToCrewRequest)(nil),  // 1: telegram.SendToCrewRequest
	(*EditMessageRequest)(nil), // 2: telegram.EditMessageRequest
	(*ReplyNoteRequest)(nil),   // 3: telegram.ReplyNoteRequest
	(*SendResult)(nil),         // 4: telegram.SendResult
}
var file_telegram_telegram_proto_depIdxs = []int32{
	0, // 0: telegram.SendResult.status:type_name -> telegram.DeliveryStatus
	1, // 1: telegram.TelegramService.SendToCrew:input_type -> telegram.SendToCrewRequest
	2, // 2: telegram.TelegramService.EditMessage:input_type -> telegram.EditMessageRequest
	3, // 3: telegram.TelegramService.ReplyNote:input_type -> telegram.ReplyNoteRequest
	4, // 4: telegram.TelegramService.SendToCrew:output_type -> telegram.SendResult
	4, // 5: telegram.TelegramService.EditMessage:output_type -> telegram.SendResult
	4, // 6: telegram.TelegramService.ReplyNote:output_type -> telegram.SendResult
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telegram_telegram_proto_init() }
func file_telegram_telegram_proto_init() {
	if File_telegram_telegram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telegram_telegram_proto_rawDesc), len(file_telegram_telegram_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telegram_telegram_proto_goTypes,
		DependencyIndexes: file_telegram_telegram_proto_depIdxs,
		EnumInfos:         file_telegram_telegram_proto_enumTypes,
		MessageInfos:      file_telegram_telegram_proto_msgTypes,
	}.Build()
	File_telegram_telegram_proto = out.File
	file_telegram_telegram_proto_goTypes = nil
	file_telegram_telegram_proto_depIdxs = nil
}
