// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: messaging/messaging.proto

package messaging

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessagingService_SyncEntityMembers_FullMethodName = "/messaging.MessagingService/SyncEntityMembers"
	MessagingService_SetEntityMembers_FullMethodName  = "/messaging.MessagingService/SetEntityMembers"
)

// MessagingServiceClient is the client API for MessagingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MessagingService provides conversation and member management via gRPC.
type MessagingServiceClient interface {
	// SyncEntityMembers adds new members to the conversation linked to an entity.
	// If the conversation does not exist yet, it returns NOT_FOUND.
	// Existing members are kept; only missing member_ids are added.
	SyncEntityMembers(ctx context.Context, in *SyncEntityMembersRequest, opts ...grpc.CallOption) (*SyncEntityMembersResponse, error)
	// SetEntityMembers sets the full member list for an entity conversation.
	// If the conversation does not exist, it creates one (entity_thread type).
	// Members not in the new list are removed; new members are added.
	SetEntityMembers(ctx context.Context, in *SetEntityMembersRequest, opts ...grpc.CallOption) (*SetEntityMembersResponse, error)
}

type messagingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagingServiceClient(cc grpc.ClientConnInterface) MessagingServiceClient {
	return &messagingServiceClient{cc}
}

func (c *messagingServiceClient) SyncEntityMembers(ctx context.Context, in *SyncEntityMembersRequest, opts ...grpc.CallOption) (*SyncEntityMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncEntityMembersResponse)
	err := c.cc.Invoke(ctx, MessagingService_SyncEntityMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) SetEntityMembers(ctx context.Context, in *SetEntityMembersRequest, opts ...grpc.CallOption) (*SetEntityMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetEntityMembersResponse)
	err := c.cc.Invoke(ctx, MessagingService_SetEntityMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagingServiceServer is the server API for MessagingService service.
// All implementations must embed UnimplementedMessagingServiceServer
// for forward compatibility.
//
// MessagingService provides conversation and member management via gRPC.
type MessagingServiceServer interface {
	// SyncEntityMembers adds new members to the conversation linked to an entity.
	// If the conversation does not exist yet, it returns NOT_FOUND.
	// Existing members are kept; only missing member_ids are added.
	SyncEntityMembers(context.Context, *SyncEntityMembersRequest) (*SyncEntityMembersResponse, error)
	// SetEntityMembers sets the full member list for an entity conversation.
	// If the conversation does not exist, it creates one (entity_thread type).
	// Members not in the new list are removed; new members are added.
	SetEntityMembers(context.Context, *SetEntityMembersRequest) (*SetEntityMembersResponse, error)
	mustEmbedUnimplementedMessagingServiceServer()
}

// UnimplementedMessagingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessagingServiceServer struct{}

func (UnimplementedMessagingServiceServer) SyncEntityMembers(context.Context, *SyncEntityMembersRequest) (*SyncEntityMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncEntityMembers not implemented")
}
func (UnimplementedMessagingServiceServer) SetEntityMembers(context.Context, *SetEntityMembersRequest) (*SetEntityMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEntityMembers not implemented")
}
func (UnimplementedMessagingServiceServer) mustEmbedUnimplementedMessagingServiceServer() {}
func (UnimplementedMessagingServiceServer) testEmbeddedByValue()                          {}

// UnsafeMessagingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessagingServiceServer will
// result in compilation errors.
type UnsafeMessagingServiceServer interface {
	mustEmbedUnimplementedMessagingServiceServer()
}

func RegisterMessagingServiceServer(s grpc.ServiceRegistrar, srv MessagingServiceServer) {
	// If the following call panics, it indicates UnimplementedMessagingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessagingService_ServiceDesc, srv)
}

func _MessagingService_SyncEntityMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncEntityMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).SyncEntityMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_SyncEntityMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).SyncEntityMembers(ctx, req.(*SyncEntityMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_SetEntityMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEntityMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).SetEntityMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_SetEntityMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).SetEntityMembers(ctx, req.(*SetEntityMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessagingService_ServiceDesc is the grpc.ServiceDesc for MessagingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessagingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messaging.MessagingService",
	HandlerType: (*MessagingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncEntityMembers",
			Handler:    _MessagingService_SyncEntityMembers_Handler,
		},
		{
			MethodName: "SetEntityMembers",
			Handler:    _MessagingService_SetEntityMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messaging/messaging.proto",
}
