// pkg/proto/loads/loads.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: loads/loads.proto

package loads

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadsService_GetRecentBrokerIDs_FullMethodName     = "/loads.LoadsService/GetRecentBrokerIDs"
	LoadsService_GetShipment_FullMethodName            = "/loads.LoadsService/GetShipment"
	LoadsService_ListShipments_FullMethodName          = "/loads.LoadsService/ListShipments"
	LoadsService_GetTrip_FullMethodName                = "/loads.LoadsService/GetTrip"
	LoadsService_ListTrips_FullMethodName              = "/loads.LoadsService/ListTrips"
	LoadsService_GetVehicleAssignments_FullMethodName  = "/loads.LoadsService/GetVehicleAssignments"
	LoadsService_UpdateVehicleLocation_FullMethodName  = "/loads.LoadsService/UpdateVehicleLocation"
	LoadsService_StreamVehicleLocations_FullMethodName = "/loads.LoadsService/StreamVehicleLocations"
)

// LoadsServiceClient is the client API for LoadsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LoadsService provides load management functionality
type LoadsServiceClient interface {
	GetRecentBrokerIDs(ctx context.Context, in *GetRecentBrokerIDsRequest, opts ...grpc.CallOption) (*GetRecentBrokerIDsResponse, error)
	// Get shipment by ID
	GetShipment(ctx context.Context, in *GetShipmentRequest, opts ...grpc.CallOption) (*ShipmentResponse, error)
	// List shipments with filters
	ListShipments(ctx context.Context, in *ListShipmentsRequest, opts ...grpc.CallOption) (*ListShipmentsResponse, error)
	// Get trip by ID
	GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	// List trips with filters
	ListTrips(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*ListTripsResponse, error)
	// Get vehicle assignments for a time range
	GetVehicleAssignments(ctx context.Context, in *GetVehicleAssignmentsRequest, opts ...grpc.CallOption) (*GetVehicleAssignmentsResponse, error)
	// Update vehicle location
	UpdateVehicleLocation(ctx context.Context, in *UpdateVehicleLocationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Stream vehicle locations
	StreamVehicleLocations(ctx context.Context, in *StreamVehicleLocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VehicleLocation], error)
}

type loadsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadsServiceClient(cc grpc.ClientConnInterface) LoadsServiceClient {
	return &loadsServiceClient{cc}
}

func (c *loadsServiceClient) GetRecentBrokerIDs(ctx context.Context, in *GetRecentBrokerIDsRequest, opts ...grpc.CallOption) (*GetRecentBrokerIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentBrokerIDsResponse)
	err := c.cc.Invoke(ctx, LoadsService_GetRecentBrokerIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadsServiceClient) GetShipment(ctx context.Context, in *GetShipmentRequest, opts ...grpc.CallOption) (*ShipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentResponse)
	err := c.cc.Invoke(ctx, LoadsService_GetShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadsServiceClient) ListShipments(ctx context.Context, in *ListShipmentsRequest, opts ...grpc.CallOption) (*ListShipmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShipmentsResponse)
	err := c.cc.Invoke(ctx, LoadsService_ListShipments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadsServiceClient) GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, LoadsService_GetTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadsServiceClient) ListTrips(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (*ListTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTripsResponse)
	err := c.cc.Invoke(ctx, LoadsService_ListTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadsServiceClient) GetVehicleAssignments(ctx context.Context, in *GetVehicleAssignmentsRequest, opts ...grpc.CallOption) (*GetVehicleAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVehicleAssignmentsResponse)
	err := c.cc.Invoke(ctx, LoadsService_GetVehicleAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadsServiceClient) UpdateVehicleLocation(ctx context.Context, in *UpdateVehicleLocationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoadsService_UpdateVehicleLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadsServiceClient) StreamVehicleLocations(ctx context.Context, in *StreamVehicleLocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VehicleLocation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoadsService_ServiceDesc.Streams[0], LoadsService_StreamVehicleLocations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamVehicleLocationsRequest, VehicleLocation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoadsService_StreamVehicleLocationsClient = grpc.ServerStreamingClient[VehicleLocation]

// LoadsServiceServer is the server API for LoadsService service.
// All implementations must embed UnimplementedLoadsServiceServer
// for forward compatibility.
//
// LoadsService provides load management functionality
type LoadsServiceServer interface {
	GetRecentBrokerIDs(context.Context, *GetRecentBrokerIDsRequest) (*GetRecentBrokerIDsResponse, error)
	// Get shipment by ID
	GetShipment(context.Context, *GetShipmentRequest) (*ShipmentResponse, error)
	// List shipments with filters
	ListShipments(context.Context, *ListShipmentsRequest) (*ListShipmentsResponse, error)
	// Get trip by ID
	GetTrip(context.Context, *GetTripRequest) (*TripResponse, error)
	// List trips with filters
	ListTrips(context.Context, *ListTripsRequest) (*ListTripsResponse, error)
	// Get vehicle assignments for a time range
	GetVehicleAssignments(context.Context, *GetVehicleAssignmentsRequest) (*GetVehicleAssignmentsResponse, error)
	// Update vehicle location
	UpdateVehicleLocation(context.Context, *UpdateVehicleLocationRequest) (*emptypb.Empty, error)
	// Stream vehicle locations
	StreamVehicleLocations(*StreamVehicleLocationsRequest, grpc.ServerStreamingServer[VehicleLocation]) error
	mustEmbedUnimplementedLoadsServiceServer()
}

// UnimplementedLoadsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadsServiceServer struct{}

func (UnimplementedLoadsServiceServer) GetRecentBrokerIDs(context.Context, *GetRecentBrokerIDsRequest) (*GetRecentBrokerIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentBrokerIDs not implemented")
}
func (UnimplementedLoadsServiceServer) GetShipment(context.Context, *GetShipmentRequest) (*ShipmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShipment not implemented")
}
func (UnimplementedLoadsServiceServer) ListShipments(context.Context, *ListShipmentsRequest) (*ListShipmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShipments not implemented")
}
func (UnimplementedLoadsServiceServer) GetTrip(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrip not implemented")
}
func (UnimplementedLoadsServiceServer) ListTrips(context.Context, *ListTripsRequest) (*ListTripsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrips not implemented")
}
func (UnimplementedLoadsServiceServer) GetVehicleAssignments(context.Context, *GetVehicleAssignmentsRequest) (*GetVehicleAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVehicleAssignments not implemented")
}
func (UnimplementedLoadsServiceServer) UpdateVehicleLocation(context.Context, *UpdateVehicleLocationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVehicleLocation not implemented")
}
func (UnimplementedLoadsServiceServer) StreamVehicleLocations(*StreamVehicleLocationsRequest, grpc.ServerStreamingServer[VehicleLocation]) error {
	return status.Error(codes.Unimplemented, "method StreamVehicleLocations not implemented")
}
func (UnimplementedLoadsServiceServer) mustEmbedUnimplementedLoadsServiceServer() {}
func (UnimplementedLoadsServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoadsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadsServiceServer will
// result in compilation errors.
type UnsafeLoadsServiceServer interface {
	mustEmbedUnimplementedLoadsServiceServer()
}

func RegisterLoadsServiceServer(s grpc.ServiceRegistrar, srv LoadsServiceServer) {
	// If the following call panics, it indicates UnimplementedLoadsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadsService_ServiceDesc, srv)
}

func _LoadsService_GetRecentBrokerIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentBrokerIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadsServiceServer).GetRecentBrokerIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadsService_GetRecentBrokerIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadsServiceServer).GetRecentBrokerIDs(ctx, req.(*GetRecentBrokerIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadsService_GetShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadsServiceServer).GetShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadsService_GetShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadsServiceServer).GetShipment(ctx, req.(*GetShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadsService_ListShipments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShipmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadsServiceServer).ListShipments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadsService_ListShipments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadsServiceServer).ListShipments(ctx, req.(*ListShipmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadsService_GetTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadsServiceServer).GetTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadsService_GetTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadsServiceServer).GetTrip(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadsService_ListTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadsServiceServer).ListTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadsService_ListTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadsServiceServer).ListTrips(ctx, req.(*ListTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadsService_GetVehicleAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadsServiceServer).GetVehicleAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadsService_GetVehicleAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadsServiceServer).GetVehicleAssignments(ctx, req.(*GetVehicleAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadsService_UpdateVehicleLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehicleLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadsServiceServer).UpdateVehicleLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadsService_UpdateVehicleLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadsServiceServer).UpdateVehicleLocation(ctx, req.(*UpdateVehicleLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadsService_StreamVehicleLocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamVehicleLocationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoadsServiceServer).StreamVehicleLocations(m, &grpc.GenericServerStream[StreamVehicleLocationsRequest, VehicleLocation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoadsService_StreamVehicleLocationsServer = grpc.ServerStreamingServer[VehicleLocation]

// LoadsService_ServiceDesc is the grpc.ServiceDesc for LoadsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loads.LoadsService",
	HandlerType: (*LoadsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecentBrokerIDs",
			Handler:    _LoadsService_GetRecentBrokerIDs_Handler,
		},
		{
			MethodName: "GetShipment",
			Handler:    _LoadsService_GetShipment_Handler,
		},
		{
			MethodName: "ListShipments",
			Handler:    _LoadsService_ListShipments_Handler,
		},
		{
			MethodName: "GetTrip",
			Handler:    _LoadsService_GetTrip_Handler,
		},
		{
			MethodName: "ListTrips",
			Handler:    _LoadsService_ListTrips_Handler,
		},
		{
			MethodName: "GetVehicleAssignments",
			Handler:    _LoadsService_GetVehicleAssignments_Handler,
		},
		{
			MethodName: "UpdateVehicleLocation",
			Handler:    _LoadsService_UpdateVehicleLocation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVehicleLocations",
			Handler:       _LoadsService_StreamVehicleLocations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loads/loads.proto",
}
