// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: files/files.proto

package files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_files_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesRequest) Reset() {
	*x = GetFilesRequest{}
	mi := &file_files_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesRequest) ProtoMessage() {}

func (x *GetFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesRequest.ProtoReflect.Descriptor instead.
func (*GetFilesRequest) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{1}
}

func (x *GetFilesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type File struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url       string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	S3Key     string                 `protobuf:"bytes,3,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Bucket    string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filename  string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType  string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Document type name from tms-files (e.g. "POD", "BOL", "RC", "INVOICE"). Empty if not classified.
	DocumentType string `protobuf:"bytes,8,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	// Document type UUID. Empty if not classified.
	DocumentTypeId string `protobuf:"bytes,9,opt,name=document_type_id,json=documentTypeId,proto3" json:"document_type_id,omitempty"`
	// Document category (e.g. "SHIPMENT", "DRIVER"). Empty if not classified.
	Category      string `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_files_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *File) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *File) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *File) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *File) GetDocumentTypeId() string {
	if x != nil {
		return x.DocumentTypeId
	}
	return ""
}

func (x *File) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_files_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type GetFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         map[string]*File       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesResponse) Reset() {
	*x = GetFilesResponse{}
	mi := &file_files_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesResponse) ProtoMessage() {}

func (x *GetFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesResponse.ProtoReflect.Descriptor instead.
func (*GetFilesResponse) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{4}
}

func (x *GetFilesResponse) GetFiles() map[string]*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type ListCompanyFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Document categories to include, e.g. ["GENERAL", "COMPANY"].
	// Tenant is implicit (actor.company_id) — not part of the request.
	Categories    []string `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompanyFilesRequest) Reset() {
	*x = ListCompanyFilesRequest{}
	mi := &file_files_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompanyFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompanyFilesRequest) ProtoMessage() {}

func (x *ListCompanyFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompanyFilesRequest.ProtoReflect.Descriptor instead.
func (*ListCompanyFilesRequest) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{5}
}

func (x *ListCompanyFilesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListCompanyFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompanyFilesResponse) Reset() {
	*x = ListCompanyFilesResponse{}
	mi := &file_files_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompanyFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompanyFilesResponse) ProtoMessage() {}

func (x *ListCompanyFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompanyFilesResponse.ProtoReflect.Descriptor instead.
func (*ListCompanyFilesResponse) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{6}
}

func (x *ListCompanyFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_files_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Oneof allows us to send metadata in the first chunk and data in others
	// Or we can just include metadata in every message (slightly more overhead)
	Chunk         []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	FileName      string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_files_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *DownloadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DownloadResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFileRequest_Meta
	//	*UploadFileRequest_Chunk
	Payload       isUploadFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_files_files_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{9}
}

func (x *UploadFileRequest) GetPayload() isUploadFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFileRequest) GetMeta() *UploadFileMeta {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Payload interface {
	isUploadFileRequest_Payload()
}

type UploadFileRequest_Meta struct {
	Meta *UploadFileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_Meta) isUploadFileRequest_Payload() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Payload() {}

type UploadFileMeta struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Filename string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// Optional. If empty, server sniffs mime from content.
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Optional. SystemPurpose name, e.g. "PAY_STATEMENT" or "USER_AVATAR".
	// Either purpose or document_type_id must be set so server can pick a FileRule.
	Purpose string `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Optional. Document type UUID; alternative to purpose for picking a FileRule
	// via document category mapping.
	DocumentTypeId string `protobuf:"bytes,4,opt,name=document_type_id,json=documentTypeId,proto3" json:"document_type_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadFileMeta) Reset() {
	*x = UploadFileMeta{}
	mi := &file_files_files_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileMeta) ProtoMessage() {}

func (x *UploadFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileMeta.ProtoReflect.Descriptor instead.
func (*UploadFileMeta) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileMeta) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileMeta) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *UploadFileMeta) GetDocumentTypeId() string {
	if x != nil {
		return x.DocumentTypeId
	}
	return ""
}

type UploadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	File  *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// True when content (by SHA256) was already stored; server returned the
	// existing record instead of creating a new one. Idempotent re-upload signal.
	WasDuplicate  bool `protobuf:"varint,2,opt,name=was_duplicate,json=wasDuplicate,proto3" json:"was_duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_files_files_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadFileResponse) GetWasDuplicate() bool {
	if x != nil {
		return x.WasDuplicate
	}
	return false
}

type DeleteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File UUID. Tenant scoping is enforced server-side, so callers cannot
	// delete files outside their company.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_files_files_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the file was found and removed; false when the id did not exist
	// (idempotent, no error). Callers can ignore unless they need exact audit.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_files_files_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFileResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_files_files_proto protoreflect.FileDescriptor

const file_files_files_proto_rawDesc = "" +
	"\n" +
	"\x11files/files.proto\x12\x05files\" \n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x0fGetFilesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x9a\x02\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x15\n" +
	"\x06s3_key\x18\x03 \x01(\tR\x05s3Key\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12#\n" +
	"\rdocument_type\x18\b \x01(\tR\fdocumentType\x12(\n" +
	"\x10document_type_id\x18\t \x01(\tR\x0edocumentTypeId\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\"2\n" +
	"\x0fGetFileResponse\x12\x1f\n" +
	"\x04file\x18\x01 \x01(\v2\v.files.FileR\x04file\"\x93\x01\n" +
	"\x10GetFilesResponse\x128\n" +
	"\x05files\x18\x01 \x03(\v2\".files.GetFilesResponse.FilesEntryR\x05files\x1aE\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.files.FileR\x05value:\x028\x01\"9\n" +
	"\x17ListCompanyFilesRequest\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"=\n" +
	"\x18ListCompanyFilesResponse\x12!\n" +
	"\x05files\x18\x01 \x03(\v2\v.files.FileR\x05files\"*\n" +
	"\x0fDownloadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"h\n" +
	"\x10DownloadResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"c\n" +
	"\x11UploadFileRequest\x12+\n" +
	"\x04meta\x18\x01 \x01(\v2\x15.files.UploadFileMetaH\x00R\x04meta\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\x0eUploadFileMeta\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12(\n" +
	"\x10document_type_id\x18\x04 \x01(\tR\x0edocumentTypeId\"Z\n" +
	"\x12UploadFileResponse\x12\x1f\n" +
	"\x04file\x18\x01 \x01(\v2\v.files.FileR\x04file\x12#\n" +
	"\rwas_duplicate\x18\x02 \x01(\bR\fwasDuplicate\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xa1\x03\n" +
	"\fFilesService\x128\n" +
	"\aGetFile\x12\x15.files.GetFileRequest\x1a\x16.files.GetFileResponse\x12;\n" +
	"\bGetFiles\x12\x16.files.GetFilesRequest\x1a\x17.files.GetFilesResponse\x12=\n" +
	"\bDownload\x12\x16.files.DownloadRequest\x1a\x17.files.DownloadResponse0\x01\x12S\n" +
	"\x10ListCompanyFiles\x12\x1e.files.ListCompanyFilesRequest\x1a\x1f.files.ListCompanyFilesResponse\x12C\n" +
	"\n" +
	"UploadFile\x12\x18.files.UploadFileRequest\x1a\x19.files.UploadFileResponse(\x01\x12A\n" +
	"\n" +
	"DeleteFile\x12\x18.files.DeleteFileRequest\x1a\x19.files.DeleteFileResponseB+Z)github.com/TMS360/backend-pkg/proto/filesb\x06proto3"

var (
	file_files_files_proto_rawDescOnce sync.Once
	file_files_files_proto_rawDescData []byte
)

func file_files_files_proto_rawDescGZIP() []byte {
	file_files_files_proto_rawDescOnce.Do(func() {
		file_files_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_files_files_proto_rawDesc), len(file_files_files_proto_rawDesc)))
	})
	return file_files_files_proto_rawDescData
}

var file_files_files_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_files_files_proto_goTypes = []any{
	(*GetFileRequest)(nil),           // 0: files.GetFileRequest
	(*GetFilesRequest)(nil),          // 1: files.GetFilesRequest
	(*File)(nil),                     // 2: files.File
	(*GetFileResponse)(nil),          // 3: files.GetFileResponse
	(*GetFilesResponse)(nil),         // 4: files.GetFilesResponse
	(*ListCompanyFilesRequest)(nil),  // 5: files.ListCompanyFilesRequest
	(*ListCompanyFilesResponse)(nil), // 6: files.ListCompanyFilesResponse
	(*DownloadRequest)(nil),          // 7: files.DownloadRequest
	(*DownloadResponse)(nil),         // 8: files.DownloadResponse
	(*UploadFileRequest)(nil),        // 9: files.UploadFileRequest
	(*UploadFileMeta)(nil),           // 10: files.UploadFileMeta
	(*UploadFileResponse)(nil),       // 11: files.UploadFileResponse
	(*DeleteFileRequest)(nil),        // 12: files.DeleteFileRequest
	(*DeleteFileResponse)(nil),       // 13: files.DeleteFileResponse
	nil,                              // 14: files.GetFilesResponse.FilesEntry
}
var file_files_files_proto_depIdxs = []int32{
	2,  // 0: files.GetFileResponse.file:type_name -> files.File
	14, // 1: files.GetFilesResponse.files:type_name -> files.GetFilesResponse.FilesEntry
	2,  // 2: files.ListCompanyFilesResponse.files:type_name -> files.File
	10, // 3: files.UploadFileRequest.meta:type_name -> files.UploadFileMeta
	2,  // 4: files.UploadFileResponse.file:type_name -> files.File
	2,  // 5: files.GetFilesResponse.FilesEntry.value:type_name -> files.File
	0,  // 6: files.FilesService.GetFile:input_type -> files.GetFileRequest
	1,  // 7: files.FilesService.GetFiles:input_type -> files.GetFilesRequest
	7,  // 8: files.FilesService.Download:input_type -> files.DownloadRequest
	5,  // 9: files.FilesService.ListCompanyFiles:input_type -> files.ListCompanyFilesRequest
	9,  // 10: files.FilesService.UploadFile:input_type -> files.UploadFileRequest
	12, // 11: files.FilesService.DeleteFile:input_type -> files.DeleteFileRequest
	3,  // 12: files.FilesService.GetFile:output_type -> files.GetFileResponse
	4,  // 13: files.FilesService.GetFiles:output_type -> files.GetFilesResponse
	8,  // 14: files.FilesService.Download:output_type -> files.DownloadResponse
	6,  // 15: files.FilesService.ListCompanyFiles:output_type -> files.ListCompanyFilesResponse
	11, // 16: files.FilesService.UploadFile:output_type -> files.UploadFileResponse
	13, // 17: files.FilesService.DeleteFile:output_type -> files.DeleteFileResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_files_files_proto_init() }
func file_files_files_proto_init() {
	if File_files_files_proto != nil {
		return
	}
	file_files_files_proto_msgTypes[9].OneofWrappers = []any{
		(*UploadFileRequest_Meta)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_files_files_proto_rawDesc), len(file_files_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_files_files_proto_goTypes,
		DependencyIndexes: file_files_files_proto_depIdxs,
		MessageInfos:      file_files_files_proto_msgTypes,
	}.Build()
	File_files_files_proto = out.File
	file_files_files_proto_goTypes = nil
	file_files_files_proto_depIdxs = nil
}
