// pkg/proto/customers/customers.proto
//
// CustomerService — server-side customer / factoring lookup used by accounting
// for tasks the Apollo Router can't fulfil (PDF render, Triumph SFTP packet,
// outbound email). NOT a replacement for the federated Customer type on
// GraphQL — frontend clients pull customer data through Apollo Federation
// (Customer @key) from this same service's GraphQL subgraph. gRPC is the
// internal channel for backend-to-backend.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: customers/customers.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerIds   []string               `protobuf:"bytes,1,rep,name=customer_ids,json=customerIds,proto3" json:"customer_ids,omitempty"` // UUIDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomersRequest) Reset() {
	*x = GetCustomersRequest{}
	mi := &file_customers_customers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomersRequest) ProtoMessage() {}

func (x *GetCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomersRequest.ProtoReflect.Descriptor instead.
func (*GetCustomersRequest) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomersRequest) GetCustomerIds() []string {
	if x != nil {
		return x.CustomerIds
	}
	return nil
}

type GetCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomersResponse) Reset() {
	*x = GetCustomersResponse{}
	mi := &file_customers_customers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomersResponse) ProtoMessage() {}

func (x *GetCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomersResponse.ProtoReflect.Descriptor instead.
func (*GetCustomersResponse) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

type Customer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyName string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	McNumber    string                 `protobuf:"bytes,3,opt,name=mc_number,json=mcNumber,proto3" json:"mc_number,omitempty"`
	// Bill-To address as a single rendered line (city, state, zip joined).
	// Empty string when not configured.
	BillingAddress string `protobuf:"bytes,4,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	// Optional factoring routing. Absent when the customer pays direct.
	Factoring *Factoring `protobuf:"bytes,5,opt,name=factoring,proto3,oneof" json:"factoring,omitempty"`
	// USDOT number from CourierCustomer.usdot. Empty string when not set.
	Usdot string `protobuf:"bytes,6,opt,name=usdot,proto3" json:"usdot,omitempty"`
	// Billing email from CustomerBilling.billing_email — where backend-accounting
	// emails the invoice PDF for direct-pay (non-factored) customers. Empty
	// string when not configured (send is blocked, mark-sent-manually allowed).
	BillingEmail  string `protobuf:"bytes,7,opt,name=billing_email,json=billingEmail,proto3" json:"billing_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_customers_customers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{2}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Customer) GetMcNumber() string {
	if x != nil {
		return x.McNumber
	}
	return ""
}

func (x *Customer) GetBillingAddress() string {
	if x != nil {
		return x.BillingAddress
	}
	return ""
}

func (x *Customer) GetFactoring() *Factoring {
	if x != nil {
		return x.Factoring
	}
	return nil
}

func (x *Customer) GetUsdot() string {
	if x != nil {
		return x.Usdot
	}
	return ""
}

func (x *Customer) GetBillingEmail() string {
	if x != nil {
		return x.BillingEmail
	}
	return ""
}

type Factoring struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CompanyName string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	// Remit-To address as a single rendered line. Empty when only the company
	// name is configured.
	RemitTo       string `protobuf:"bytes,2,opt,name=remit_to,json=remitTo,proto3" json:"remit_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Factoring) Reset() {
	*x = Factoring{}
	mi := &file_customers_customers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Factoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factoring) ProtoMessage() {}

func (x *Factoring) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factoring.ProtoReflect.Descriptor instead.
func (*Factoring) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{3}
}

func (x *Factoring) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Factoring) GetRemitTo() string {
	if x != nil {
		return x.RemitTo
	}
	return ""
}

var File_customers_customers_proto protoreflect.FileDescriptor

const file_customers_customers_proto_rawDesc = "" +
	"\n" +
	"\x19customers/customers.proto\x12\tcustomers\"8\n" +
	"\x13GetCustomersRequest\x12!\n" +
	"\fcustomer_ids\x18\x01 \x03(\tR\vcustomerIds\"I\n" +
	"\x14GetCustomersResponse\x121\n" +
	"\tcustomers\x18\x01 \x03(\v2\x13.customers.CustomerR\tcustomers\"\x85\x02\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12\x1b\n" +
	"\tmc_number\x18\x03 \x01(\tR\bmcNumber\x12'\n" +
	"\x0fbilling_address\x18\x04 \x01(\tR\x0ebillingAddress\x127\n" +
	"\tfactoring\x18\x05 \x01(\v2\x14.customers.FactoringH\x00R\tfactoring\x88\x01\x01\x12\x14\n" +
	"\x05usdot\x18\x06 \x01(\tR\x05usdot\x12#\n" +
	"\rbilling_email\x18\a \x01(\tR\fbillingEmailB\f\n" +
	"\n" +
	"_factoring\"I\n" +
	"\tFactoring\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12\x19\n" +
	"\bremit_to\x18\x02 \x01(\tR\aremitTo2b\n" +
	"\x0fCustomerService\x12O\n" +
	"\fGetCustomers\x12\x1e.customers.GetCustomersRequest\x1a\x1f.customers.GetCustomersResponseB/Z-github.com/TMS360/backend-pkg/proto/customersb\x06proto3"

var (
	file_customers_customers_proto_rawDescOnce sync.Once
	file_customers_customers_proto_rawDescData []byte
)

func file_customers_customers_proto_rawDescGZIP() []byte {
	file_customers_customers_proto_rawDescOnce.Do(func() {
		file_customers_customers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_customers_proto_rawDesc), len(file_customers_customers_proto_rawDesc)))
	})
	return file_customers_customers_proto_rawDescData
}

var file_customers_customers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_customers_customers_proto_goTypes = []any{
	(*GetCustomersRequest)(nil),  // 0: customers.GetCustomersRequest
	(*GetCustomersResponse)(nil), // 1: customers.GetCustomersResponse
	(*Customer)(nil),             // 2: customers.Customer
	(*Factoring)(nil),            // 3: customers.Factoring
}
var file_customers_customers_proto_depIdxs = []int32{
	2, // 0: customers.GetCustomersResponse.customers:type_name -> customers.Customer
	3, // 1: customers.Customer.factoring:type_name -> customers.Factoring
	0, // 2: customers.CustomerService.GetCustomers:input_type -> customers.GetCustomersRequest
	1, // 3: customers.CustomerService.GetCustomers:output_type -> customers.GetCustomersResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_customers_customers_proto_init() }
func file_customers_customers_proto_init() {
	if File_customers_customers_proto != nil {
		return
	}
	file_customers_customers_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_customers_proto_rawDesc), len(file_customers_customers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customers_customers_proto_goTypes,
		DependencyIndexes: file_customers_customers_proto_depIdxs,
		MessageInfos:      file_customers_customers_proto_msgTypes,
	}.Build()
	File_customers_customers_proto = out.File
	file_customers_customers_proto_goTypes = nil
	file_customers_customers_proto_depIdxs = nil
}
