// pkg/proto/customers/customers.proto
//
// CustomerService — server-side customer / factoring lookup used by accounting
// for tasks the Apollo Router can't fulfil (PDF render, Triumph SFTP packet,
// outbound email). NOT a replacement for the federated Customer type on
// GraphQL — frontend clients pull customer data through Apollo Federation
// (Customer @key) from this same service's GraphQL subgraph. gRPC is the
// internal channel for backend-to-backend.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: customers/customers.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerIds   []string               `protobuf:"bytes,1,rep,name=customer_ids,json=customerIds,proto3" json:"customer_ids,omitempty"` // UUIDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomersRequest) Reset() {
	*x = GetCustomersRequest{}
	mi := &file_customers_customers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomersRequest) ProtoMessage() {}

func (x *GetCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomersRequest.ProtoReflect.Descriptor instead.
func (*GetCustomersRequest) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomersRequest) GetCustomerIds() []string {
	if x != nil {
		return x.CustomerIds
	}
	return nil
}

type GetCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomersResponse) Reset() {
	*x = GetCustomersResponse{}
	mi := &file_customers_customers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomersResponse) ProtoMessage() {}

func (x *GetCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomersResponse.ProtoReflect.Descriptor instead.
func (*GetCustomersResponse) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

type Customer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyName string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	McNumber    string                 `protobuf:"bytes,3,opt,name=mc_number,json=mcNumber,proto3" json:"mc_number,omitempty"`
	// Bill-To address as a single rendered line (city, state, zip joined).
	// Empty string when not configured.
	BillingAddress string `protobuf:"bytes,4,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	// Optional factoring routing. Absent when the customer pays direct.
	Factoring *Factoring `protobuf:"bytes,5,opt,name=factoring,proto3,oneof" json:"factoring,omitempty"`
	// USDOT number from CourierCustomer.usdot. Empty string when not set.
	Usdot string `protobuf:"bytes,6,opt,name=usdot,proto3" json:"usdot,omitempty"`
	// Billing email from CustomerBilling.billing_email — where backend-accounting
	// emails the invoice PDF for direct-pay (non-factored) customers. Empty
	// string when not configured (send is blocked, mark-sent-manually allowed).
	BillingEmail string `protobuf:"bytes,7,opt,name=billing_email,json=billingEmail,proto3" json:"billing_email,omitempty"`
	// Payment terms in net days from CustomerBilling.terms_day (Net 30 → 30).
	// Absent when not configured — accounting then leaves the invoice's existing
	// terms / due date untouched.
	TermsDay *int32 `protobuf:"varint,8,opt,name=terms_day,json=termsDay,proto3,oneof" json:"terms_day,omitempty"`
	// The company this customer belongs to (DEV-2025).
	//
	// GetCustomers answers with a system actor on purpose — accounting calls it
	// for PDF and SFTP work that is not tied to a user session — so the response
	// is NOT tenant-scoped and a caller that looks a customer up by id alone
	// cannot tell whether it is even its own. Carrying the owner lets the caller
	// decide; without it, "customer exists" and "customer exists in MY company"
	// are the same answer, which is how a load ends up billed to a stranger.
	//
	// Empty string only for a row saved before the field existed.
	CompanyId string `protobuf:"bytes,9,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// CustomerBilling.billing_type as the enums.BillingType string
	// (FACTORING_COMPANY / EMAIL / MANUAL / WEB_PORTAL / EDI) (DEV-2282).
	//
	// Absent when the customer has NO billing row yet — nobody has confirmed how
	// this broker is billed. `factoring` alone cannot say that: it is nil both for
	// a direct-pay broker and for an unreviewed one, and accounting must not send
	// an unreviewed broker to the factor or park it in the direct queue.
	BillingType   *string `protobuf:"bytes,10,opt,name=billing_type,json=billingType,proto3,oneof" json:"billing_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_customers_customers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{2}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Customer) GetMcNumber() string {
	if x != nil {
		return x.McNumber
	}
	return ""
}

func (x *Customer) GetBillingAddress() string {
	if x != nil {
		return x.BillingAddress
	}
	return ""
}

func (x *Customer) GetFactoring() *Factoring {
	if x != nil {
		return x.Factoring
	}
	return nil
}

func (x *Customer) GetUsdot() string {
	if x != nil {
		return x.Usdot
	}
	return ""
}

func (x *Customer) GetBillingEmail() string {
	if x != nil {
		return x.BillingEmail
	}
	return ""
}

func (x *Customer) GetTermsDay() int32 {
	if x != nil && x.TermsDay != nil {
		return *x.TermsDay
	}
	return 0
}

func (x *Customer) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Customer) GetBillingType() string {
	if x != nil && x.BillingType != nil {
		return *x.BillingType
	}
	return ""
}

type Factoring struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CompanyName string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	// Remit-To address as a single rendered line. Empty when only the company
	// name is configured.
	RemitTo       string `protobuf:"bytes,2,opt,name=remit_to,json=remitTo,proto3" json:"remit_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Factoring) Reset() {
	*x = Factoring{}
	mi := &file_customers_customers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Factoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factoring) ProtoMessage() {}

func (x *Factoring) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factoring.ProtoReflect.Descriptor instead.
func (*Factoring) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{3}
}

func (x *Factoring) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Factoring) GetRemitTo() string {
	if x != nil {
		return x.RemitTo
	}
	return ""
}

type GetCustomerPolicyFactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`       // tenant UUID (required)
	CustomerIds   []string               `protobuf:"bytes,2,rep,name=customer_ids,json=customerIds,proto3" json:"customer_ids,omitempty"` // UUIDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerPolicyFactsRequest) Reset() {
	*x = GetCustomerPolicyFactsRequest{}
	mi := &file_customers_customers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerPolicyFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerPolicyFactsRequest) ProtoMessage() {}

func (x *GetCustomerPolicyFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerPolicyFactsRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerPolicyFactsRequest) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerPolicyFactsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetCustomerPolicyFactsRequest) GetCustomerIds() []string {
	if x != nil {
		return x.CustomerIds
	}
	return nil
}

type GetCustomerPolicyFactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*CustomerPolicyFacts `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerPolicyFactsResponse) Reset() {
	*x = GetCustomerPolicyFactsResponse{}
	mi := &file_customers_customers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerPolicyFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerPolicyFactsResponse) ProtoMessage() {}

func (x *GetCustomerPolicyFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerPolicyFactsResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerPolicyFactsResponse) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerPolicyFactsResponse) GetCustomers() []*CustomerPolicyFacts {
	if x != nil {
		return x.Customers
	}
	return nil
}

type CustomerPolicyFacts struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CustomerId         string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CustomerType       string                 `protobuf:"bytes,3,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	BrokerGroup        *string                `protobuf:"bytes,4,opt,name=broker_group,json=brokerGroup,proto3,oneof" json:"broker_group,omitempty"`
	DriverInstructions string                 `protobuf:"bytes,5,opt,name=driver_instructions,json=driverInstructions,proto3" json:"driver_instructions,omitempty"`
	Warnings           []*ActiveWarning       `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"` // only non-expired warnings
	Credit             *CreditFacts           `protobuf:"bytes,7,opt,name=credit,proto3,oneof" json:"credit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CustomerPolicyFacts) Reset() {
	*x = CustomerPolicyFacts{}
	mi := &file_customers_customers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerPolicyFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerPolicyFacts) ProtoMessage() {}

func (x *CustomerPolicyFacts) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerPolicyFacts.ProtoReflect.Descriptor instead.
func (*CustomerPolicyFacts) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{6}
}

func (x *CustomerPolicyFacts) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerPolicyFacts) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CustomerPolicyFacts) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *CustomerPolicyFacts) GetBrokerGroup() string {
	if x != nil && x.BrokerGroup != nil {
		return *x.BrokerGroup
	}
	return ""
}

func (x *CustomerPolicyFacts) GetDriverInstructions() string {
	if x != nil {
		return x.DriverInstructions
	}
	return ""
}

func (x *CustomerPolicyFacts) GetWarnings() []*ActiveWarning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CustomerPolicyFacts) GetCredit() *CreditFacts {
	if x != nil {
		return x.Credit
	}
	return nil
}

type ActiveWarning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreditLimit   *float64               `protobuf:"fixed64,3,opt,name=credit_limit,json=creditLimit,proto3,oneof" json:"credit_limit,omitempty"`
	ExpiresAt     *string                `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"` // RFC3339; unset = never expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveWarning) Reset() {
	*x = ActiveWarning{}
	mi := &file_customers_customers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveWarning) ProtoMessage() {}

func (x *ActiveWarning) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveWarning.ProtoReflect.Descriptor instead.
func (*ActiveWarning) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{7}
}

func (x *ActiveWarning) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActiveWarning) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActiveWarning) GetCreditLimit() float64 {
	if x != nil && x.CreditLimit != nil {
		return *x.CreditLimit
	}
	return 0
}

func (x *ActiveWarning) GetExpiresAt() string {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return ""
}

type CreditFacts struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreditScore     *float64               `protobuf:"fixed64,1,opt,name=credit_score,json=creditScore,proto3,oneof" json:"credit_score,omitempty"`
	CreditRate      *string                `protobuf:"bytes,2,opt,name=credit_rate,json=creditRate,proto3,oneof" json:"credit_rate,omitempty"`
	ApprovalStatus  *string                `protobuf:"bytes,3,opt,name=approval_status,json=approvalStatus,proto3,oneof" json:"approval_status,omitempty"`
	DaysToPay       *int32                 `protobuf:"varint,4,opt,name=days_to_pay,json=daysToPay,proto3,oneof" json:"days_to_pay,omitempty"`
	RtsInvoiceCount *int32                 `protobuf:"varint,5,opt,name=rts_invoice_count,json=rtsInvoiceCount,proto3,oneof" json:"rts_invoice_count,omitempty"`
	RtsScore        *string                `protobuf:"bytes,6,opt,name=rts_score,json=rtsScore,proto3,oneof" json:"rts_score,omitempty"`
	RtsAsOf         *string                `protobuf:"bytes,7,opt,name=rts_as_of,json=rtsAsOf,proto3,oneof" json:"rts_as_of,omitempty"` // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreditFacts) Reset() {
	*x = CreditFacts{}
	mi := &file_customers_customers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditFacts) ProtoMessage() {}

func (x *CreditFacts) ProtoReflect() protoreflect.Message {
	mi := &file_customers_customers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditFacts.ProtoReflect.Descriptor instead.
func (*CreditFacts) Descriptor() ([]byte, []int) {
	return file_customers_customers_proto_rawDescGZIP(), []int{8}
}

func (x *CreditFacts) GetCreditScore() float64 {
	if x != nil && x.CreditScore != nil {
		return *x.CreditScore
	}
	return 0
}

func (x *CreditFacts) GetCreditRate() string {
	if x != nil && x.CreditRate != nil {
		return *x.CreditRate
	}
	return ""
}

func (x *CreditFacts) GetApprovalStatus() string {
	if x != nil && x.ApprovalStatus != nil {
		return *x.ApprovalStatus
	}
	return ""
}

func (x *CreditFacts) GetDaysToPay() int32 {
	if x != nil && x.DaysToPay != nil {
		return *x.DaysToPay
	}
	return 0
}

func (x *CreditFacts) GetRtsInvoiceCount() int32 {
	if x != nil && x.RtsInvoiceCount != nil {
		return *x.RtsInvoiceCount
	}
	return 0
}

func (x *CreditFacts) GetRtsScore() string {
	if x != nil && x.RtsScore != nil {
		return *x.RtsScore
	}
	return ""
}

func (x *CreditFacts) GetRtsAsOf() string {
	if x != nil && x.RtsAsOf != nil {
		return *x.RtsAsOf
	}
	return ""
}

var File_customers_customers_proto protoreflect.FileDescriptor

const file_customers_customers_proto_rawDesc = "" +
	"\n" +
	"\x19customers/customers.proto\x12\tcustomers\"8\n" +
	"\x13GetCustomersRequest\x12!\n" +
	"\fcustomer_ids\x18\x01 \x03(\tR\vcustomerIds\"I\n" +
	"\x14GetCustomersResponse\x121\n" +
	"\tcustomers\x18\x01 \x03(\v2\x13.customers.CustomerR\tcustomers\"\x8d\x03\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12\x1b\n" +
	"\tmc_number\x18\x03 \x01(\tR\bmcNumber\x12'\n" +
	"\x0fbilling_address\x18\x04 \x01(\tR\x0ebillingAddress\x127\n" +
	"\tfactoring\x18\x05 \x01(\v2\x14.customers.FactoringH\x00R\tfactoring\x88\x01\x01\x12\x14\n" +
	"\x05usdot\x18\x06 \x01(\tR\x05usdot\x12#\n" +
	"\rbilling_email\x18\a \x01(\tR\fbillingEmail\x12 \n" +
	"\tterms_day\x18\b \x01(\x05H\x01R\btermsDay\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"company_id\x18\t \x01(\tR\tcompanyId\x12&\n" +
	"\fbilling_type\x18\n" +
	" \x01(\tH\x02R\vbillingType\x88\x01\x01B\f\n" +
	"\n" +
	"_factoringB\f\n" +
	"\n" +
	"_terms_dayB\x0f\n" +
	"\r_billing_type\"I\n" +
	"\tFactoring\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12\x19\n" +
	"\bremit_to\x18\x02 \x01(\tR\aremitTo\"a\n" +
	"\x1dGetCustomerPolicyFactsRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12!\n" +
	"\fcustomer_ids\x18\x02 \x03(\tR\vcustomerIds\"^\n" +
	"\x1eGetCustomerPolicyFactsResponse\x12<\n" +
	"\tcustomers\x18\x01 \x03(\v2\x1e.customers.CustomerPolicyFactsR\tcustomers\"\xd3\x02\n" +
	"\x13CustomerPolicyFacts\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcustomer_type\x18\x03 \x01(\tR\fcustomerType\x12&\n" +
	"\fbroker_group\x18\x04 \x01(\tH\x00R\vbrokerGroup\x88\x01\x01\x12/\n" +
	"\x13driver_instructions\x18\x05 \x01(\tR\x12driverInstructions\x124\n" +
	"\bwarnings\x18\x06 \x03(\v2\x18.customers.ActiveWarningR\bwarnings\x123\n" +
	"\x06credit\x18\a \x01(\v2\x16.customers.CreditFactsH\x01R\x06credit\x88\x01\x01B\x0f\n" +
	"\r_broker_groupB\t\n" +
	"\a_credit\"\xa5\x01\n" +
	"\rActiveWarning\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12&\n" +
	"\fcredit_limit\x18\x03 \x01(\x01H\x00R\vcreditLimit\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tH\x01R\texpiresAt\x88\x01\x01B\x0f\n" +
	"\r_credit_limitB\r\n" +
	"\v_expires_at\"\x99\x03\n" +
	"\vCreditFacts\x12&\n" +
	"\fcredit_score\x18\x01 \x01(\x01H\x00R\vcreditScore\x88\x01\x01\x12$\n" +
	"\vcredit_rate\x18\x02 \x01(\tH\x01R\n" +
	"creditRate\x88\x01\x01\x12,\n" +
	"\x0fapproval_status\x18\x03 \x01(\tH\x02R\x0eapprovalStatus\x88\x01\x01\x12#\n" +
	"\vdays_to_pay\x18\x04 \x01(\x05H\x03R\tdaysToPay\x88\x01\x01\x12/\n" +
	"\x11rts_invoice_count\x18\x05 \x01(\x05H\x04R\x0frtsInvoiceCount\x88\x01\x01\x12 \n" +
	"\trts_score\x18\x06 \x01(\tH\x05R\brtsScore\x88\x01\x01\x12\x1f\n" +
	"\trts_as_of\x18\a \x01(\tH\x06R\artsAsOf\x88\x01\x01B\x0f\n" +
	"\r_credit_scoreB\x0e\n" +
	"\f_credit_rateB\x12\n" +
	"\x10_approval_statusB\x0e\n" +
	"\f_days_to_payB\x14\n" +
	"\x12_rts_invoice_countB\f\n" +
	"\n" +
	"_rts_scoreB\f\n" +
	"\n" +
	"_rts_as_of2\xd1\x01\n" +
	"\x0fCustomerService\x12O\n" +
	"\fGetCustomers\x12\x1e.customers.GetCustomersRequest\x1a\x1f.customers.GetCustomersResponse\x12m\n" +
	"\x16GetCustomerPolicyFacts\x12(.customers.GetCustomerPolicyFactsRequest\x1a).customers.GetCustomerPolicyFactsResponseB/Z-github.com/TMS360/backend-pkg/proto/customersb\x06proto3"

var (
	file_customers_customers_proto_rawDescOnce sync.Once
	file_customers_customers_proto_rawDescData []byte
)

func file_customers_customers_proto_rawDescGZIP() []byte {
	file_customers_customers_proto_rawDescOnce.Do(func() {
		file_customers_customers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_customers_proto_rawDesc), len(file_customers_customers_proto_rawDesc)))
	})
	return file_customers_customers_proto_rawDescData
}

var file_customers_customers_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_customers_customers_proto_goTypes = []any{
	(*GetCustomersRequest)(nil),            // 0: customers.GetCustomersRequest
	(*GetCustomersResponse)(nil),           // 1: customers.GetCustomersResponse
	(*Customer)(nil),                       // 2: customers.Customer
	(*Factoring)(nil),                      // 3: customers.Factoring
	(*GetCustomerPolicyFactsRequest)(nil),  // 4: customers.GetCustomerPolicyFactsRequest
	(*GetCustomerPolicyFactsResponse)(nil), // 5: customers.GetCustomerPolicyFactsResponse
	(*CustomerPolicyFacts)(nil),            // 6: customers.CustomerPolicyFacts
	(*ActiveWarning)(nil),                  // 7: customers.ActiveWarning
	(*CreditFacts)(nil),                    // 8: customers.CreditFacts
}
var file_customers_customers_proto_depIdxs = []int32{
	2, // 0: customers.GetCustomersResponse.customers:type_name -> customers.Customer
	3, // 1: customers.Customer.factoring:type_name -> customers.Factoring
	6, // 2: customers.GetCustomerPolicyFactsResponse.customers:type_name -> customers.CustomerPolicyFacts
	7, // 3: customers.CustomerPolicyFacts.warnings:type_name -> customers.ActiveWarning
	8, // 4: customers.CustomerPolicyFacts.credit:type_name -> customers.CreditFacts
	0, // 5: customers.CustomerService.GetCustomers:input_type -> customers.GetCustomersRequest
	4, // 6: customers.CustomerService.GetCustomerPolicyFacts:input_type -> customers.GetCustomerPolicyFactsRequest
	1, // 7: customers.CustomerService.GetCustomers:output_type -> customers.GetCustomersResponse
	5, // 8: customers.CustomerService.GetCustomerPolicyFacts:output_type -> customers.GetCustomerPolicyFactsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_customers_customers_proto_init() }
func file_customers_customers_proto_init() {
	if File_customers_customers_proto != nil {
		return
	}
	file_customers_customers_proto_msgTypes[2].OneofWrappers = []any{}
	file_customers_customers_proto_msgTypes[6].OneofWrappers = []any{}
	file_customers_customers_proto_msgTypes[7].OneofWrappers = []any{}
	file_customers_customers_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_customers_proto_rawDesc), len(file_customers_customers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customers_customers_proto_goTypes,
		DependencyIndexes: file_customers_customers_proto_depIdxs,
		MessageInfos:      file_customers_customers_proto_msgTypes,
	}.Build()
	File_customers_customers_proto = out.File
	file_customers_customers_proto_goTypes = nil
	file_customers_customers_proto_depIdxs = nil
}
