// pkg/proto/tasks/tasks.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: tasks/tasks.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DedupKey identifies the specific validation occurrence a task belongs to.
// The whole key together is what "the same problem" means; exactly one live
// task exists per key.
type DedupKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RuleId             string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`                                     // the rule that fired
	EntityType         string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                         // load | trip | driver | document | ...
	EntityId           string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`                               // the TMS entity the task concerns (UUID)
	ValidationInstance string                 `protobuf:"bytes,4,opt,name=validation_instance,json=validationInstance,proto3" json:"validation_instance,omitempty"` // the specific check that triggered
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DedupKey) Reset() {
	*x = DedupKey{}
	mi := &file_tasks_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DedupKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DedupKey) ProtoMessage() {}

func (x *DedupKey) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DedupKey.ProtoReflect.Descriptor instead.
func (*DedupKey) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *DedupKey) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DedupKey) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *DedupKey) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *DedupKey) GetValidationInstance() string {
	if x != nil {
		return x.ValidationInstance
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *DedupKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`                             // low|normal|high|urgent — empty = normal
	AssigneeType  string                 `protobuf:"bytes,5,opt,name=assignee_type,json=assigneeType,proto3" json:"assignee_type,omitempty"` // user|department|role|all
	AssigneeId    string                 `protobuf:"bytes,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`       // UUID; required unless assignee_type = "all"
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`                      // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_tasks_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetKey() *DedupKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTaskRequest) GetAssigneeType() string {
	if x != nil {
		return x.AssigneeType
	}
	return ""
}

func (x *CreateTaskRequest) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *CreateTaskRequest) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`    // "open" on a fresh task; current status if it already existed
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"` // true = new task; false = existing one returned (dup/retry)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_tasks_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTaskResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ResolveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *DedupKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // optional; recorded on the system status change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTaskRequest) Reset() {
	*x = ResolveTaskRequest{}
	mi := &file_tasks_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTaskRequest) ProtoMessage() {}

func (x *ResolveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTaskRequest.ProtoReflect.Descriptor instead.
func (*ResolveTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveTaskRequest) GetKey() *DedupKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ResolveTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResolveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // the resolved task, or empty when nothing was open
	Resolved      bool                   `protobuf:"varint,2,opt,name=resolved,proto3" json:"resolved,omitempty"`          // true = a task was auto-resolved; false = no-op
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTaskResponse) Reset() {
	*x = ResolveTaskResponse{}
	mi := &file_tasks_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTaskResponse) ProtoMessage() {}

func (x *ResolveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTaskResponse.ProtoReflect.Descriptor instead.
func (*ResolveTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResolveTaskResponse) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

// ListOpenAuditChecksRequest asks about ONE team-week, named by the crew-week
// rows the caller is about to sign off. The caller owns the board, so it knows
// its crews; this service never calls the dispatch service back to find them.
type ListOpenAuditChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrewIds       []string               `protobuf:"bytes,1,rep,name=crew_ids,json=crewIds,proto3" json:"crew_ids,omitempty"`       // UUIDs; empty = nothing to ask about
	WeekStart     string                 `protobuf:"bytes,2,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"` // YYYY-MM-DD, the naive company-local week start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenAuditChecksRequest) Reset() {
	*x = ListOpenAuditChecksRequest{}
	mi := &file_tasks_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenAuditChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenAuditChecksRequest) ProtoMessage() {}

func (x *ListOpenAuditChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenAuditChecksRequest.ProtoReflect.Descriptor instead.
func (*ListOpenAuditChecksRequest) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *ListOpenAuditChecksRequest) GetCrewIds() []string {
	if x != nil {
		return x.CrewIds
	}
	return nil
}

func (x *ListOpenAuditChecksRequest) GetWeekStart() string {
	if x != nil {
		return x.WeekStart
	}
	return ""
}

// OpenAuditCheck is one check still waiting for an answer — exactly what a
// refusal has to name so the manager knows who to go and ask.
type OpenAuditCheck struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TaskId     string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CrewId     string                 `protobuf:"bytes,2,opt,name=crew_id,json=crewId,proto3" json:"crew_id,omitempty"`
	Day        string                 `protobuf:"bytes,3,opt,name=day,proto3" json:"day,omitempty"`                                 // YYYY-MM-DD, the day under question
	StatusName string                 `protobuf:"bytes,4,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"` // what the dispatcher closed the day with
	// department is the well-known key of the department that owes the answer
	// ("maintenance", "safety", …). Empty when the check was never routed to one.
	Department    string `protobuf:"bytes,5,opt,name=department,proto3" json:"department,omitempty"`
	Title         string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAuditCheck) Reset() {
	*x = OpenAuditCheck{}
	mi := &file_tasks_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAuditCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAuditCheck) ProtoMessage() {}

func (x *OpenAuditCheck) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAuditCheck.ProtoReflect.Descriptor instead.
func (*OpenAuditCheck) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *OpenAuditCheck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *OpenAuditCheck) GetCrewId() string {
	if x != nil {
		return x.CrewId
	}
	return ""
}

func (x *OpenAuditCheck) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *OpenAuditCheck) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *OpenAuditCheck) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *OpenAuditCheck) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListOpenAuditChecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*OpenAuditCheck      `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenAuditChecksResponse) Reset() {
	*x = ListOpenAuditChecksResponse{}
	mi := &file_tasks_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenAuditChecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenAuditChecksResponse) ProtoMessage() {}

func (x *ListOpenAuditChecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenAuditChecksResponse.ProtoReflect.Descriptor instead.
func (*ListOpenAuditChecksResponse) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *ListOpenAuditChecksResponse) GetChecks() []*OpenAuditCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

// CreateAuditCheckRequest is the whole claim in ONE call: the tasks service
// must be able to show the card, refuse a self-answer and open a rejection's
// incident without ever calling the dispatch service back. Dates are naive
// company-local YYYY-MM-DD strings, never instants (DEV-2076).
type CreateAuditCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The day under question and what it was closed with.
	Day         string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`                              // YYYY-MM-DD
	WeekStart   string `protobuf:"bytes,2,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"` // YYYY-MM-DD
	StatusName  string `protobuf:"bytes,3,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	Explanation string `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`                 // optional
	CaseNumber  string `protobuf:"bytes,5,opt,name=case_number,json=caseNumber,proto3" json:"case_number,omitempty"` // optional, e.g. "WO-1182"
	// The crew-week the day belongs to, and who set it. BOTH are empty on a
	// truck-day-with-no-driver check: no crew held the truck and nobody set a
	// status — the system noticed the gap.
	CrewId string `protobuf:"bytes,6,opt,name=crew_id,json=crewId,proto3" json:"crew_id,omitempty"` // UUID or empty
	SetBy  string `protobuf:"bytes,7,opt,name=set_by,json=setBy,proto3" json:"set_by,omitempty"`    // UUID or empty
	// Who answers, and who may not.
	Department     string   `protobuf:"bytes,8,opt,name=department,proto3" json:"department,omitempty"`                                  // well-known key ("maintenance", …)
	DispatcherIds  []string `protobuf:"bytes,9,rep,name=dispatcher_ids,json=dispatcherIds,proto3" json:"dispatcher_ids,omitempty"`       // UUIDs; nobody here may answer
	ManagerId      string   `protobuf:"bytes,10,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`                  // UUID or empty
	DispatchTeamId string   `protobuf:"bytes,11,opt,name=dispatch_team_id,json=dispatchTeamId,proto3" json:"dispatch_team_id,omitempty"` // UUID or empty
	// What the day is about — the crew's truck, or its driver when it has none.
	EntityType    string `protobuf:"bytes,12,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // truck | driver
	EntityId      string `protobuf:"bytes,13,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`       // UUID
	Title         string `protobuf:"bytes,14,opt,name=title,proto3" json:"title,omitempty"`                             // optional; empty = generated from status + day
	Description   string `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`                 // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditCheckRequest) Reset() {
	*x = CreateAuditCheckRequest{}
	mi := &file_tasks_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditCheckRequest) ProtoMessage() {}

func (x *CreateAuditCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditCheckRequest.ProtoReflect.Descriptor instead.
func (*CreateAuditCheckRequest) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAuditCheckRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetWeekStart() string {
	if x != nil {
		return x.WeekStart
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetCaseNumber() string {
	if x != nil {
		return x.CaseNumber
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetCrewId() string {
	if x != nil {
		return x.CrewId
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetDispatcherIds() []string {
	if x != nil {
		return x.DispatcherIds
	}
	return nil
}

func (x *CreateAuditCheckRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetDispatchTeamId() string {
	if x != nil {
		return x.DispatchTeamId
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAuditCheckRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateAuditCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // false = the same claim's check already existed (retry)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditCheckResponse) Reset() {
	*x = CreateAuditCheckResponse{}
	mi := &file_tasks_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditCheckResponse) ProtoMessage() {}

func (x *CreateAuditCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditCheckResponse.ProtoReflect.Descriptor instead.
func (*CreateAuditCheckResponse) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAuditCheckResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateAuditCheckResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetAuditCheckAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditCheckAnswerRequest) Reset() {
	*x = GetAuditCheckAnswerRequest{}
	mi := &file_tasks_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditCheckAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditCheckAnswerRequest) ProtoMessage() {}

func (x *GetAuditCheckAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditCheckAnswerRequest.ProtoReflect.Descriptor instead.
func (*GetAuditCheckAnswerRequest) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *GetAuditCheckAnswerRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetAuditCheckAnswerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// answered=false means the check is still open; every other field is then
	// zero. It is NOT an error — "no verdict yet" is the answer.
	Answered      bool                   `protobuf:"varint,1,opt,name=answered,proto3" json:"answered,omitempty"`
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`                         // CONFIRMED | REJECTED
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`                               // the department's words; mandatory on a reject
	AnsweredBy    string                 `protobuf:"bytes,4,opt,name=answered_by,json=answeredBy,proto3" json:"answered_by,omitempty"` // UUID
	AnsweredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=answered_at,json=answeredAt,proto3" json:"answered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditCheckAnswerResponse) Reset() {
	*x = GetAuditCheckAnswerResponse{}
	mi := &file_tasks_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditCheckAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditCheckAnswerResponse) ProtoMessage() {}

func (x *GetAuditCheckAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditCheckAnswerResponse.ProtoReflect.Descriptor instead.
func (*GetAuditCheckAnswerResponse) Descriptor() ([]byte, []int) {
	return file_tasks_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *GetAuditCheckAnswerResponse) GetAnswered() bool {
	if x != nil {
		return x.Answered
	}
	return false
}

func (x *GetAuditCheckAnswerResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *GetAuditCheckAnswerResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GetAuditCheckAnswerResponse) GetAnsweredBy() string {
	if x != nil {
		return x.AnsweredBy
	}
	return ""
}

func (x *GetAuditCheckAnswerResponse) GetAnsweredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnsweredAt
	}
	return nil
}

var File_tasks_tasks_proto protoreflect.FileDescriptor

const file_tasks_tasks_proto_rawDesc = "" +
	"\n" +
	"\x11tasks/tasks.proto\x12\x05tasks\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\bDedupKey\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12/\n" +
	"\x13validation_instance\x18\x04 \x01(\tR\x12validationInstance\"\x83\x02\n" +
	"\x11CreateTaskRequest\x12!\n" +
	"\x03key\x18\x01 \x01(\v2\x0f.tasks.DedupKeyR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12#\n" +
	"\rassignee_type\x18\x05 \x01(\tR\fassigneeType\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\tR\n" +
	"assigneeId\x121\n" +
	"\x06due_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\"_\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\"O\n" +
	"\x12ResolveTaskRequest\x12!\n" +
	"\x03key\x18\x01 \x01(\v2\x0f.tasks.DedupKeyR\x03key\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x13ResolveTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bresolved\x18\x02 \x01(\bR\bresolved\"V\n" +
	"\x1aListOpenAuditChecksRequest\x12\x19\n" +
	"\bcrew_ids\x18\x01 \x03(\tR\acrewIds\x12\x1d\n" +
	"\n" +
	"week_start\x18\x02 \x01(\tR\tweekStart\"\xab\x01\n" +
	"\x0eOpenAuditCheck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\acrew_id\x18\x02 \x01(\tR\x06crewId\x12\x10\n" +
	"\x03day\x18\x03 \x01(\tR\x03day\x12\x1f\n" +
	"\vstatus_name\x18\x04 \x01(\tR\n" +
	"statusName\x12\x1e\n" +
	"\n" +
	"department\x18\x05 \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\"L\n" +
	"\x1bListOpenAuditChecksResponse\x12-\n" +
	"\x06checks\x18\x01 \x03(\v2\x15.tasks.OpenAuditCheckR\x06checks\"\xe4\x03\n" +
	"\x17CreateAuditCheckRequest\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x1d\n" +
	"\n" +
	"week_start\x18\x02 \x01(\tR\tweekStart\x12\x1f\n" +
	"\vstatus_name\x18\x03 \x01(\tR\n" +
	"statusName\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12\x1f\n" +
	"\vcase_number\x18\x05 \x01(\tR\n" +
	"caseNumber\x12\x17\n" +
	"\acrew_id\x18\x06 \x01(\tR\x06crewId\x12\x15\n" +
	"\x06set_by\x18\a \x01(\tR\x05setBy\x12\x1e\n" +
	"\n" +
	"department\x18\b \x01(\tR\n" +
	"department\x12%\n" +
	"\x0edispatcher_ids\x18\t \x03(\tR\rdispatcherIds\x12\x1d\n" +
	"\n" +
	"manager_id\x18\n" +
	" \x01(\tR\tmanagerId\x12(\n" +
	"\x10dispatch_team_id\x18\v \x01(\tR\x0edispatchTeamId\x12\x1f\n" +
	"\ventity_type\x18\f \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\r \x01(\tR\bentityId\x12\x14\n" +
	"\x05title\x18\x0e \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\"M\n" +
	"\x18CreateAuditCheckResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"5\n" +
	"\x1aGetAuditCheckAnswerRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc5\x01\n" +
	"\x1bGetAuditCheckAnswerResponse\x12\x1a\n" +
	"\banswered\x18\x01 \x01(\bR\banswered\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x1f\n" +
	"\vanswered_by\x18\x04 \x01(\tR\n" +
	"answeredBy\x12;\n" +
	"\vanswered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"answeredAt2\xa8\x03\n" +
	"\fTasksService\x12A\n" +
	"\n" +
	"CreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x12D\n" +
	"\vResolveTask\x12\x19.tasks.ResolveTaskRequest\x1a\x1a.tasks.ResolveTaskResponse\x12\\\n" +
	"\x13ListOpenAuditChecks\x12!.tasks.ListOpenAuditChecksRequest\x1a\".tasks.ListOpenAuditChecksResponse\x12S\n" +
	"\x10CreateAuditCheck\x12\x1e.tasks.CreateAuditCheckRequest\x1a\x1f.tasks.CreateAuditCheckResponse\x12\\\n" +
	"\x13GetAuditCheckAnswer\x12!.tasks.GetAuditCheckAnswerRequest\x1a\".tasks.GetAuditCheckAnswerResponseB+Z)github.com/TMS360/backend-pkg/proto/tasksb\x06proto3"

var (
	file_tasks_tasks_proto_rawDescOnce sync.Once
	file_tasks_tasks_proto_rawDescData []byte
)

func file_tasks_tasks_proto_rawDescGZIP() []byte {
	file_tasks_tasks_proto_rawDescOnce.Do(func() {
		file_tasks_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_tasks_proto_rawDesc), len(file_tasks_tasks_proto_rawDesc)))
	})
	return file_tasks_tasks_proto_rawDescData
}

var file_tasks_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tasks_tasks_proto_goTypes = []any{
	(*DedupKey)(nil),                    // 0: tasks.DedupKey
	(*CreateTaskRequest)(nil),           // 1: tasks.CreateTaskRequest
	(*CreateTaskResponse)(nil),          // 2: tasks.CreateTaskResponse
	(*ResolveTaskRequest)(nil),          // 3: tasks.ResolveTaskRequest
	(*ResolveTaskResponse)(nil),         // 4: tasks.ResolveTaskResponse
	(*ListOpenAuditChecksRequest)(nil),  // 5: tasks.ListOpenAuditChecksRequest
	(*OpenAuditCheck)(nil),              // 6: tasks.OpenAuditCheck
	(*ListOpenAuditChecksResponse)(nil), // 7: tasks.ListOpenAuditChecksResponse
	(*CreateAuditCheckRequest)(nil),     // 8: tasks.CreateAuditCheckRequest
	(*CreateAuditCheckResponse)(nil),    // 9: tasks.CreateAuditCheckResponse
	(*GetAuditCheckAnswerRequest)(nil),  // 10: tasks.GetAuditCheckAnswerRequest
	(*GetAuditCheckAnswerResponse)(nil), // 11: tasks.GetAuditCheckAnswerResponse
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_tasks_tasks_proto_depIdxs = []int32{
	0,  // 0: tasks.CreateTaskRequest.key:type_name -> tasks.DedupKey
	12, // 1: tasks.CreateTaskRequest.due_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tasks.ResolveTaskRequest.key:type_name -> tasks.DedupKey
	6,  // 3: tasks.ListOpenAuditChecksResponse.checks:type_name -> tasks.OpenAuditCheck
	12, // 4: tasks.GetAuditCheckAnswerResponse.answered_at:type_name -> google.protobuf.Timestamp
	1,  // 5: tasks.TasksService.CreateTask:input_type -> tasks.CreateTaskRequest
	3,  // 6: tasks.TasksService.ResolveTask:input_type -> tasks.ResolveTaskRequest
	5,  // 7: tasks.TasksService.ListOpenAuditChecks:input_type -> tasks.ListOpenAuditChecksRequest
	8,  // 8: tasks.TasksService.CreateAuditCheck:input_type -> tasks.CreateAuditCheckRequest
	10, // 9: tasks.TasksService.GetAuditCheckAnswer:input_type -> tasks.GetAuditCheckAnswerRequest
	2,  // 10: tasks.TasksService.CreateTask:output_type -> tasks.CreateTaskResponse
	4,  // 11: tasks.TasksService.ResolveTask:output_type -> tasks.ResolveTaskResponse
	7,  // 12: tasks.TasksService.ListOpenAuditChecks:output_type -> tasks.ListOpenAuditChecksResponse
	9,  // 13: tasks.TasksService.CreateAuditCheck:output_type -> tasks.CreateAuditCheckResponse
	11, // 14: tasks.TasksService.GetAuditCheckAnswer:output_type -> tasks.GetAuditCheckAnswerResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tasks_tasks_proto_init() }
func file_tasks_tasks_proto_init() {
	if File_tasks_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_tasks_proto_rawDesc), len(file_tasks_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_tasks_proto_goTypes,
		DependencyIndexes: file_tasks_tasks_proto_depIdxs,
		MessageInfos:      file_tasks_tasks_proto_msgTypes,
	}.Build()
	File_tasks_tasks_proto = out.File
	file_tasks_tasks_proto_goTypes = nil
	file_tasks_tasks_proto_depIdxs = nil
}
