// pkg/proto/trackers/trackers.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: trackers/trackers.proto

package trackers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackersService_StreamVehicleVINs_FullMethodName = "/trackers.TrackersService/StreamVehicleVINs"
)

// TrackersServiceClient is the client API for TrackersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TrackersService provides vehicle tracking functionality
type TrackersServiceClient interface {
	// StreamVehicleVINs sends a stream of VINs from backend-load to samsara-tracker
	StreamVehicleVINs(ctx context.Context, in *StreamVehicleVINsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VehicleVIN], error)
}

type trackersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackersServiceClient(cc grpc.ClientConnInterface) TrackersServiceClient {
	return &trackersServiceClient{cc}
}

func (c *trackersServiceClient) StreamVehicleVINs(ctx context.Context, in *StreamVehicleVINsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VehicleVIN], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrackersService_ServiceDesc.Streams[0], TrackersService_StreamVehicleVINs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamVehicleVINsRequest, VehicleVIN]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackersService_StreamVehicleVINsClient = grpc.ServerStreamingClient[VehicleVIN]

// TrackersServiceServer is the server API for TrackersService service.
// All implementations must embed UnimplementedTrackersServiceServer
// for forward compatibility.
//
// TrackersService provides vehicle tracking functionality
type TrackersServiceServer interface {
	// StreamVehicleVINs sends a stream of VINs from backend-load to samsara-tracker
	StreamVehicleVINs(*StreamVehicleVINsRequest, grpc.ServerStreamingServer[VehicleVIN]) error
	mustEmbedUnimplementedTrackersServiceServer()
}

// UnimplementedTrackersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackersServiceServer struct{}

func (UnimplementedTrackersServiceServer) StreamVehicleVINs(*StreamVehicleVINsRequest, grpc.ServerStreamingServer[VehicleVIN]) error {
	return status.Error(codes.Unimplemented, "method StreamVehicleVINs not implemented")
}
func (UnimplementedTrackersServiceServer) mustEmbedUnimplementedTrackersServiceServer() {}
func (UnimplementedTrackersServiceServer) testEmbeddedByValue()                         {}

// UnsafeTrackersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackersServiceServer will
// result in compilation errors.
type UnsafeTrackersServiceServer interface {
	mustEmbedUnimplementedTrackersServiceServer()
}

func RegisterTrackersServiceServer(s grpc.ServiceRegistrar, srv TrackersServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackersService_ServiceDesc, srv)
}

func _TrackersService_StreamVehicleVINs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamVehicleVINsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrackersServiceServer).StreamVehicleVINs(m, &grpc.GenericServerStream[StreamVehicleVINsRequest, VehicleVIN]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackersService_StreamVehicleVINsServer = grpc.ServerStreamingServer[VehicleVIN]

// TrackersService_ServiceDesc is the grpc.ServiceDesc for TrackersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trackers.TrackersService",
	HandlerType: (*TrackersServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVehicleVINs",
			Handler:       _TrackersService_StreamVehicleVINs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trackers/trackers.proto",
}
