// pkg/proto/trackers/trackers.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: trackers/trackers.proto

package trackers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of vehicle
type VehicleType int32

const (
	VehicleType_VEHICLE_TYPE_UNSPECIFIED VehicleType = 0
	VehicleType_VEHICLE_TYPE_TRUCK       VehicleType = 1
	VehicleType_VEHICLE_TYPE_TRAILER     VehicleType = 2
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "VEHICLE_TYPE_UNSPECIFIED",
		1: "VEHICLE_TYPE_TRUCK",
		2: "VEHICLE_TYPE_TRAILER",
	}
	VehicleType_value = map[string]int32{
		"VEHICLE_TYPE_UNSPECIFIED": 0,
		"VEHICLE_TYPE_TRUCK":       1,
		"VEHICLE_TYPE_TRAILER":     2,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_trackers_trackers_proto_enumTypes[0].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_trackers_trackers_proto_enumTypes[0]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{0}
}

// Request to stream vehicle VINs
type StreamVehicleVINsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: include only active vehicles
	ActiveOnly bool `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	// Optional: last sync timestamp to get only updates
	LastSync      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVehicleVINsRequest) Reset() {
	*x = StreamVehicleVINsRequest{}
	mi := &file_trackers_trackers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVehicleVINsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVehicleVINsRequest) ProtoMessage() {}

func (x *StreamVehicleVINsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVehicleVINsRequest.ProtoReflect.Descriptor instead.
func (*StreamVehicleVINsRequest) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{0}
}

func (x *StreamVehicleVINsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *StreamVehicleVINsRequest) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSync
	}
	return nil
}

// Vehicle VIN information
type VehicleVIN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // UUID of truck or trailer
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`                              // Vehicle Identification Number
	Type          VehicleType            `protobuf:"varint,3,opt,name=type,proto3,enum=trackers.VehicleType" json:"type,omitempty"` // Type of vehicle
	Number        string                 `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`                        // Vehicle number
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompanyId     string                 `protobuf:"bytes,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Company ID for grouping vehicles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleVIN) Reset() {
	*x = VehicleVIN{}
	mi := &file_trackers_trackers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleVIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleVIN) ProtoMessage() {}

func (x *VehicleVIN) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleVIN.ProtoReflect.Descriptor instead.
func (*VehicleVIN) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleVIN) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VehicleVIN) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleVIN) GetType() VehicleType {
	if x != nil {
		return x.Type
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *VehicleVIN) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *VehicleVIN) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *VehicleVIN) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Location update message for Kafka
type VehicleLocationUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                        // UUID of truck or trailer
	Vin               string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`                                                      // Vehicle Identification Number
	Type              VehicleType            `protobuf:"varint,3,opt,name=type,proto3,enum=trackers.VehicleType" json:"type,omitempty"`                         // Type of vehicle
	Latitude          float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`                                          // Latitude coordinate
	Longitude         float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`                                        // Longitude coordinate
	Heading           float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`                                            // Heading in degrees
	Speed             float64                `protobuf:"fixed64,7,opt,name=speed,proto3" json:"speed,omitempty"`                                                // Speed in mph
	Address           string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`                                              // Address name
	FormattedLocation string                 `protobuf:"bytes,9,opt,name=formatted_location,json=formattedLocation,proto3" json:"formatted_location,omitempty"` // Formatted location string
	GpsTime           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=gps_time,json=gpsTime,proto3" json:"gps_time,omitempty"`                              // GPS timestamp
	SamsaraVehicleId  string                 `protobuf:"bytes,11,opt,name=samsara_vehicle_id,json=samsaraVehicleId,proto3" json:"samsara_vehicle_id,omitempty"` // Samsara's vehicle ID
	VehicleName       string                 `protobuf:"bytes,12,opt,name=vehicle_name,json=vehicleName,proto3" json:"vehicle_name,omitempty"`                  // Vehicle name from Samsara
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VehicleLocationUpdate) Reset() {
	*x = VehicleLocationUpdate{}
	mi := &file_trackers_trackers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleLocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleLocationUpdate) ProtoMessage() {}

func (x *VehicleLocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleLocationUpdate.ProtoReflect.Descriptor instead.
func (*VehicleLocationUpdate) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleLocationUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VehicleLocationUpdate) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleLocationUpdate) GetType() VehicleType {
	if x != nil {
		return x.Type
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *VehicleLocationUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *VehicleLocationUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *VehicleLocationUpdate) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *VehicleLocationUpdate) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *VehicleLocationUpdate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VehicleLocationUpdate) GetFormattedLocation() string {
	if x != nil {
		return x.FormattedLocation
	}
	return ""
}

func (x *VehicleLocationUpdate) GetGpsTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GpsTime
	}
	return nil
}

func (x *VehicleLocationUpdate) GetSamsaraVehicleId() string {
	if x != nil {
		return x.SamsaraVehicleId
	}
	return ""
}

func (x *VehicleLocationUpdate) GetVehicleName() string {
	if x != nil {
		return x.VehicleName
	}
	return ""
}

// Batch of location updates for Kafka
type VehicleLocationUpdateBatch struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Updates       []*VehicleLocationUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	BatchTime     *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=batch_time,json=batchTime,proto3" json:"batch_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleLocationUpdateBatch) Reset() {
	*x = VehicleLocationUpdateBatch{}
	mi := &file_trackers_trackers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleLocationUpdateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleLocationUpdateBatch) ProtoMessage() {}

func (x *VehicleLocationUpdateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleLocationUpdateBatch.ProtoReflect.Descriptor instead.
func (*VehicleLocationUpdateBatch) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{3}
}

func (x *VehicleLocationUpdateBatch) GetUpdates() []*VehicleLocationUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *VehicleLocationUpdateBatch) GetBatchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BatchTime
	}
	return nil
}

type GetVehicleRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckId       string                 `protobuf:"bytes,1,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRouteRequest) Reset() {
	*x = GetVehicleRouteRequest{}
	mi := &file_trackers_trackers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRouteRequest) ProtoMessage() {}

func (x *GetVehicleRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRouteRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRouteRequest) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{4}
}

func (x *GetVehicleRouteRequest) GetTruckId() string {
	if x != nil {
		return x.TruckId
	}
	return ""
}

func (x *GetVehicleRouteRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetVehicleRouteRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type RoutePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Heading       float64                `protobuf:"fixed64,3,opt,name=heading,proto3" json:"heading,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	GpsTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=gps_time,json=gpsTime,proto3" json:"gps_time,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePoint) Reset() {
	*x = RoutePoint{}
	mi := &file_trackers_trackers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePoint) ProtoMessage() {}

func (x *RoutePoint) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePoint.ProtoReflect.Descriptor instead.
func (*RoutePoint) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{5}
}

func (x *RoutePoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RoutePoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RoutePoint) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *RoutePoint) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *RoutePoint) GetGpsTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GpsTime
	}
	return nil
}

func (x *RoutePoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetVehicleRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*RoutePoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRouteResponse) Reset() {
	*x = GetVehicleRouteResponse{}
	mi := &file_trackers_trackers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRouteResponse) ProtoMessage() {}

func (x *GetVehicleRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRouteResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleRouteResponse) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{6}
}

func (x *GetVehicleRouteResponse) GetPoints() []*RoutePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type EstimatedRouteLeg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LegIndex        int32                  `protobuf:"varint,1,opt,name=leg_index,json=legIndex,proto3" json:"leg_index,omitempty"`
	Polyline        string                 `protobuf:"bytes,2,opt,name=polyline,proto3" json:"polyline,omitempty"` // HERE Flexible Polyline encoded string
	DistanceMeters  int32                  `protobuf:"varint,3,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstimatedRouteLeg) Reset() {
	*x = EstimatedRouteLeg{}
	mi := &file_trackers_trackers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimatedRouteLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatedRouteLeg) ProtoMessage() {}

func (x *EstimatedRouteLeg) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatedRouteLeg.ProtoReflect.Descriptor instead.
func (*EstimatedRouteLeg) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{7}
}

func (x *EstimatedRouteLeg) GetLegIndex() int32 {
	if x != nil {
		return x.LegIndex
	}
	return 0
}

func (x *EstimatedRouteLeg) GetPolyline() string {
	if x != nil {
		return x.Polyline
	}
	return ""
}

func (x *EstimatedRouteLeg) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *EstimatedRouteLeg) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type SaveEstimatedRouteRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TripId               string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	CompanyId            string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Legs                 []*EstimatedRouteLeg   `protobuf:"bytes,3,rep,name=legs,proto3" json:"legs,omitempty"`
	TotalDistanceMeters  int32                  `protobuf:"varint,4,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	TotalDurationSeconds int32                  `protobuf:"varint,5,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SaveEstimatedRouteRequest) Reset() {
	*x = SaveEstimatedRouteRequest{}
	mi := &file_trackers_trackers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveEstimatedRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEstimatedRouteRequest) ProtoMessage() {}

func (x *SaveEstimatedRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEstimatedRouteRequest.ProtoReflect.Descriptor instead.
func (*SaveEstimatedRouteRequest) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{8}
}

func (x *SaveEstimatedRouteRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *SaveEstimatedRouteRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *SaveEstimatedRouteRequest) GetLegs() []*EstimatedRouteLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *SaveEstimatedRouteRequest) GetTotalDistanceMeters() int32 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *SaveEstimatedRouteRequest) GetTotalDurationSeconds() int32 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

type SaveEstimatedRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveEstimatedRouteResponse) Reset() {
	*x = SaveEstimatedRouteResponse{}
	mi := &file_trackers_trackers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveEstimatedRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEstimatedRouteResponse) ProtoMessage() {}

func (x *SaveEstimatedRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEstimatedRouteResponse.ProtoReflect.Descriptor instead.
func (*SaveEstimatedRouteResponse) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{9}
}

func (x *SaveEstimatedRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEstimatedRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimatedRouteRequest) Reset() {
	*x = GetEstimatedRouteRequest{}
	mi := &file_trackers_trackers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimatedRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatedRouteRequest) ProtoMessage() {}

func (x *GetEstimatedRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatedRouteRequest.ProtoReflect.Descriptor instead.
func (*GetEstimatedRouteRequest) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{10}
}

func (x *GetEstimatedRouteRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type GetEstimatedRouteResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TripId               string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Legs                 []*EstimatedRouteLeg   `protobuf:"bytes,2,rep,name=legs,proto3" json:"legs,omitempty"`
	TotalDistanceMeters  int32                  `protobuf:"varint,3,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	TotalDurationSeconds int32                  `protobuf:"varint,4,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetEstimatedRouteResponse) Reset() {
	*x = GetEstimatedRouteResponse{}
	mi := &file_trackers_trackers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimatedRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatedRouteResponse) ProtoMessage() {}

func (x *GetEstimatedRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trackers_trackers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatedRouteResponse.ProtoReflect.Descriptor instead.
func (*GetEstimatedRouteResponse) Descriptor() ([]byte, []int) {
	return file_trackers_trackers_proto_rawDescGZIP(), []int{11}
}

func (x *GetEstimatedRouteResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *GetEstimatedRouteResponse) GetLegs() []*EstimatedRouteLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *GetEstimatedRouteResponse) GetTotalDistanceMeters() int32 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *GetEstimatedRouteResponse) GetTotalDurationSeconds() int32 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

var File_trackers_trackers_proto protoreflect.FileDescriptor

const file_trackers_trackers_proto_rawDesc = "" +
	"\n" +
	"\x17trackers/trackers.proto\x12\btrackers\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n" +
	"\x18StreamVehicleVINsRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x127\n" +
	"\tlast_sync\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSync\"\xcb\x01\n" +
	"\n" +
	"VehicleVIN\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.trackers.VehicleTypeR\x04type\x12\x16\n" +
	"\x06number\x18\x04 \x01(\tR\x06number\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"company_id\x18\x06 \x01(\tR\tcompanyId\"\x9f\x03\n" +
	"\x15VehicleLocationUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.trackers.VehicleTypeR\x04type\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\a \x01(\x01R\x05speed\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12-\n" +
	"\x12formatted_location\x18\t \x01(\tR\x11formattedLocation\x125\n" +
	"\bgps_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\agpsTime\x12,\n" +
	"\x12samsara_vehicle_id\x18\v \x01(\tR\x10samsaraVehicleId\x12!\n" +
	"\fvehicle_name\x18\f \x01(\tR\vvehicleName\"\x92\x01\n" +
	"\x1aVehicleLocationUpdateBatch\x129\n" +
	"\aupdates\x18\x01 \x03(\v2\x1f.trackers.VehicleLocationUpdateR\aupdates\x129\n" +
	"\n" +
	"batch_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tbatchTime\"\x8f\x01\n" +
	"\x16GetVehicleRouteRequest\x12\x19\n" +
	"\btruck_id\x18\x01 \x01(\tR\atruckId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xc7\x01\n" +
	"\n" +
	"RoutePoint\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aheading\x18\x03 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x125\n" +
	"\bgps_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\agpsTime\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"G\n" +
	"\x17GetVehicleRouteResponse\x12,\n" +
	"\x06points\x18\x01 \x03(\v2\x14.trackers.RoutePointR\x06points\"\xa0\x01\n" +
	"\x11EstimatedRouteLeg\x12\x1b\n" +
	"\tleg_index\x18\x01 \x01(\x05R\blegIndex\x12\x1a\n" +
	"\bpolyline\x18\x02 \x01(\tR\bpolyline\x12'\n" +
	"\x0fdistance_meters\x18\x03 \x01(\x05R\x0edistanceMeters\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\"\xee\x01\n" +
	"\x19SaveEstimatedRouteRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12/\n" +
	"\x04legs\x18\x03 \x03(\v2\x1b.trackers.EstimatedRouteLegR\x04legs\x122\n" +
	"\x15total_distance_meters\x18\x04 \x01(\x05R\x13totalDistanceMeters\x124\n" +
	"\x16total_duration_seconds\x18\x05 \x01(\x05R\x14totalDurationSeconds\"6\n" +
	"\x1aSaveEstimatedRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x18GetEstimatedRouteRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"\xcf\x01\n" +
	"\x19GetEstimatedRouteResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12/\n" +
	"\x04legs\x18\x02 \x03(\v2\x1b.trackers.EstimatedRouteLegR\x04legs\x122\n" +
	"\x15total_distance_meters\x18\x03 \x01(\x05R\x13totalDistanceMeters\x124\n" +
	"\x16total_duration_seconds\x18\x04 \x01(\x05R\x14totalDurationSeconds*]\n" +
	"\vVehicleType\x12\x1c\n" +
	"\x18VEHICLE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VEHICLE_TYPE_TRUCK\x10\x01\x12\x18\n" +
	"\x14VEHICLE_TYPE_TRAILER\x10\x022b\n" +
	"\x0fTrackersService\x12O\n" +
	"\x11StreamVehicleVINs\x12\".trackers.StreamVehicleVINsRequest\x1a\x14.trackers.VehicleVIN0\x012\xaf\x02\n" +
	"\x16VehiclePositionService\x12V\n" +
	"\x0fGetVehicleRoute\x12 .trackers.GetVehicleRouteRequest\x1a!.trackers.GetVehicleRouteResponse\x12_\n" +
	"\x12SaveEstimatedRoute\x12#.trackers.SaveEstimatedRouteRequest\x1a$.trackers.SaveEstimatedRouteResponse\x12\\\n" +
	"\x11GetEstimatedRoute\x12\".trackers.GetEstimatedRouteRequest\x1a#.trackers.GetEstimatedRouteResponseB.Z,github.com/TMS360/backend-pkg/proto/trackersb\x06proto3"

var (
	file_trackers_trackers_proto_rawDescOnce sync.Once
	file_trackers_trackers_proto_rawDescData []byte
)

func file_trackers_trackers_proto_rawDescGZIP() []byte {
	file_trackers_trackers_proto_rawDescOnce.Do(func() {
		file_trackers_trackers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trackers_trackers_proto_rawDesc), len(file_trackers_trackers_proto_rawDesc)))
	})
	return file_trackers_trackers_proto_rawDescData
}

var file_trackers_trackers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trackers_trackers_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_trackers_trackers_proto_goTypes = []any{
	(VehicleType)(0),                   // 0: trackers.VehicleType
	(*StreamVehicleVINsRequest)(nil),   // 1: trackers.StreamVehicleVINsRequest
	(*VehicleVIN)(nil),                 // 2: trackers.VehicleVIN
	(*VehicleLocationUpdate)(nil),      // 3: trackers.VehicleLocationUpdate
	(*VehicleLocationUpdateBatch)(nil), // 4: trackers.VehicleLocationUpdateBatch
	(*GetVehicleRouteRequest)(nil),     // 5: trackers.GetVehicleRouteRequest
	(*RoutePoint)(nil),                 // 6: trackers.RoutePoint
	(*GetVehicleRouteResponse)(nil),    // 7: trackers.GetVehicleRouteResponse
	(*EstimatedRouteLeg)(nil),          // 8: trackers.EstimatedRouteLeg
	(*SaveEstimatedRouteRequest)(nil),  // 9: trackers.SaveEstimatedRouteRequest
	(*SaveEstimatedRouteResponse)(nil), // 10: trackers.SaveEstimatedRouteResponse
	(*GetEstimatedRouteRequest)(nil),   // 11: trackers.GetEstimatedRouteRequest
	(*GetEstimatedRouteResponse)(nil),  // 12: trackers.GetEstimatedRouteResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_trackers_trackers_proto_depIdxs = []int32{
	13, // 0: trackers.StreamVehicleVINsRequest.last_sync:type_name -> google.protobuf.Timestamp
	0,  // 1: trackers.VehicleVIN.type:type_name -> trackers.VehicleType
	13, // 2: trackers.VehicleVIN.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: trackers.VehicleLocationUpdate.type:type_name -> trackers.VehicleType
	13, // 4: trackers.VehicleLocationUpdate.gps_time:type_name -> google.protobuf.Timestamp
	3,  // 5: trackers.VehicleLocationUpdateBatch.updates:type_name -> trackers.VehicleLocationUpdate
	13, // 6: trackers.VehicleLocationUpdateBatch.batch_time:type_name -> google.protobuf.Timestamp
	13, // 7: trackers.GetVehicleRouteRequest.from:type_name -> google.protobuf.Timestamp
	13, // 8: trackers.GetVehicleRouteRequest.to:type_name -> google.protobuf.Timestamp
	13, // 9: trackers.RoutePoint.gps_time:type_name -> google.protobuf.Timestamp
	6,  // 10: trackers.GetVehicleRouteResponse.points:type_name -> trackers.RoutePoint
	8,  // 11: trackers.SaveEstimatedRouteRequest.legs:type_name -> trackers.EstimatedRouteLeg
	8,  // 12: trackers.GetEstimatedRouteResponse.legs:type_name -> trackers.EstimatedRouteLeg
	1,  // 13: trackers.TrackersService.StreamVehicleVINs:input_type -> trackers.StreamVehicleVINsRequest
	5,  // 14: trackers.VehiclePositionService.GetVehicleRoute:input_type -> trackers.GetVehicleRouteRequest
	9,  // 15: trackers.VehiclePositionService.SaveEstimatedRoute:input_type -> trackers.SaveEstimatedRouteRequest
	11, // 16: trackers.VehiclePositionService.GetEstimatedRoute:input_type -> trackers.GetEstimatedRouteRequest
	2,  // 17: trackers.TrackersService.StreamVehicleVINs:output_type -> trackers.VehicleVIN
	7,  // 18: trackers.VehiclePositionService.GetVehicleRoute:output_type -> trackers.GetVehicleRouteResponse
	10, // 19: trackers.VehiclePositionService.SaveEstimatedRoute:output_type -> trackers.SaveEstimatedRouteResponse
	12, // 20: trackers.VehiclePositionService.GetEstimatedRoute:output_type -> trackers.GetEstimatedRouteResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_trackers_trackers_proto_init() }
func file_trackers_trackers_proto_init() {
	if File_trackers_trackers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trackers_trackers_proto_rawDesc), len(file_trackers_trackers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_trackers_trackers_proto_goTypes,
		DependencyIndexes: file_trackers_trackers_proto_depIdxs,
		EnumInfos:         file_trackers_trackers_proto_enumTypes,
		MessageInfos:      file_trackers_trackers_proto_msgTypes,
	}.Build()
	File_trackers_trackers_proto = out.File
	file_trackers_trackers_proto_goTypes = nil
	file_trackers_trackers_proto_depIdxs = nil
}
