// pkg/proto/audit/audit.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: audit/audit.proto

package audit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditFacts_CountEvents_FullMethodName = "/audit.AuditFacts/CountEvents"
)

// AuditFactsClient is the client API for AuditFacts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditFacts serves counts over the audit trail for RMS facts that the
// consuming services (load, teams, accounting) declare with rules.Provide.
type AuditFactsClient interface {
	// company_id, entity_types, from and to are required; to > from and the
	// window is at most 400 days. The server answers codes.InvalidArgument
	// otherwise and never runs the read unscoped.
	CountEvents(ctx context.Context, in *CountEventsRequest, opts ...grpc.CallOption) (*CountEventsResponse, error)
}

type auditFactsClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditFactsClient(cc grpc.ClientConnInterface) AuditFactsClient {
	return &auditFactsClient{cc}
}

func (c *auditFactsClient) CountEvents(ctx context.Context, in *CountEventsRequest, opts ...grpc.CallOption) (*CountEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountEventsResponse)
	err := c.cc.Invoke(ctx, AuditFacts_CountEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditFactsServer is the server API for AuditFacts service.
// All implementations must embed UnimplementedAuditFactsServer
// for forward compatibility.
//
// AuditFacts serves counts over the audit trail for RMS facts that the
// consuming services (load, teams, accounting) declare with rules.Provide.
type AuditFactsServer interface {
	// company_id, entity_types, from and to are required; to > from and the
	// window is at most 400 days. The server answers codes.InvalidArgument
	// otherwise and never runs the read unscoped.
	CountEvents(context.Context, *CountEventsRequest) (*CountEventsResponse, error)
	mustEmbedUnimplementedAuditFactsServer()
}

// UnimplementedAuditFactsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditFactsServer struct{}

func (UnimplementedAuditFactsServer) CountEvents(context.Context, *CountEventsRequest) (*CountEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountEvents not implemented")
}
func (UnimplementedAuditFactsServer) mustEmbedUnimplementedAuditFactsServer() {}
func (UnimplementedAuditFactsServer) testEmbeddedByValue()                    {}

// UnsafeAuditFactsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditFactsServer will
// result in compilation errors.
type UnsafeAuditFactsServer interface {
	mustEmbedUnimplementedAuditFactsServer()
}

func RegisterAuditFactsServer(s grpc.ServiceRegistrar, srv AuditFactsServer) {
	// If the following call panics, it indicates UnimplementedAuditFactsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditFacts_ServiceDesc, srv)
}

func _AuditFacts_CountEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditFactsServer).CountEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditFacts_CountEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditFactsServer).CountEvents(ctx, req.(*CountEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditFacts_ServiceDesc is the grpc.ServiceDesc for AuditFacts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditFacts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit.AuditFacts",
	HandlerType: (*AuditFactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountEvents",
			Handler:    _AuditFacts_CountEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit/audit.proto",
}
