// pkg/proto/audit/audit.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit/audit.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`             // tenant UUID (required); never from the token alone
	EntityTypes   []string               `protobuf:"bytes,2,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`       // required, at least one
	Actions       []string               `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`                                  // optional
	ParticipantId string                 `protobuf:"bytes,4,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"` // optional (driver / dispatcher / user)
	EntityId      string                 `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`                // optional
	ChangedFields []string               `protobuf:"bytes,6,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"` // optional: match changes[].field
	ActorId       string                 `protobuf:"bytes,7,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`                   // optional
	From          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=from,proto3" json:"from,omitempty"`                                        // required
	To            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`                                            // required, exclusive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountEventsRequest) Reset() {
	*x = CountEventsRequest{}
	mi := &file_audit_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountEventsRequest) ProtoMessage() {}

func (x *CountEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountEventsRequest.ProtoReflect.Descriptor instead.
func (*CountEventsRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *CountEventsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CountEventsRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *CountEventsRequest) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CountEventsRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *CountEventsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CountEventsRequest) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

func (x *CountEventsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CountEventsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CountEventsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type CountEventsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Count  int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`                // distinct event_id
	LastAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_at,json=lastAt,proto3" json:"last_at,omitempty"` // unset when count = 0
	// Earliest row of these entity_types for the company. A caller whose from
	// is before covered_from must treat the fact as unknown, not as zero.
	CoveredFrom   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=covered_from,json=coveredFrom,proto3" json:"covered_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountEventsResponse) Reset() {
	*x = CountEventsResponse{}
	mi := &file_audit_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountEventsResponse) ProtoMessage() {}

func (x *CountEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountEventsResponse.ProtoReflect.Descriptor instead.
func (*CountEventsResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{1}
}

func (x *CountEventsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CountEventsResponse) GetLastAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAt
	}
	return nil
}

func (x *CountEventsResponse) GetCoveredFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CoveredFrom
	}
	return nil
}

var File_audit_audit_proto protoreflect.FileDescriptor

const file_audit_audit_proto_rawDesc = "" +
	"\n" +
	"\x11audit/audit.proto\x12\x05audit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x02\n" +
	"\x12CountEventsRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12!\n" +
	"\fentity_types\x18\x02 \x03(\tR\ventityTypes\x12\x18\n" +
	"\aactions\x18\x03 \x03(\tR\aactions\x12%\n" +
	"\x0eparticipant_id\x18\x04 \x01(\tR\rparticipantId\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x12%\n" +
	"\x0echanged_fields\x18\x06 \x03(\tR\rchangedFields\x12\x19\n" +
	"\bactor_id\x18\a \x01(\tR\aactorId\x12.\n" +
	"\x04from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\x9f\x01\n" +
	"\x13CountEventsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x123\n" +
	"\alast_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06lastAt\x12=\n" +
	"\fcovered_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcoveredFrom2R\n" +
	"\n" +
	"AuditFacts\x12D\n" +
	"\vCountEvents\x12\x19.audit.CountEventsRequest\x1a\x1a.audit.CountEventsResponseB+Z)github.com/TMS360/backend-pkg/proto/auditb\x06proto3"

var (
	file_audit_audit_proto_rawDescOnce sync.Once
	file_audit_audit_proto_rawDescData []byte
)

func file_audit_audit_proto_rawDescGZIP() []byte {
	file_audit_audit_proto_rawDescOnce.Do(func() {
		file_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)))
	})
	return file_audit_audit_proto_rawDescData
}

var file_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audit_audit_proto_goTypes = []any{
	(*CountEventsRequest)(nil),    // 0: audit.CountEventsRequest
	(*CountEventsResponse)(nil),   // 1: audit.CountEventsResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_audit_audit_proto_depIdxs = []int32{
	2, // 0: audit.CountEventsRequest.from:type_name -> google.protobuf.Timestamp
	2, // 1: audit.CountEventsRequest.to:type_name -> google.protobuf.Timestamp
	2, // 2: audit.CountEventsResponse.last_at:type_name -> google.protobuf.Timestamp
	2, // 3: audit.CountEventsResponse.covered_from:type_name -> google.protobuf.Timestamp
	0, // 4: audit.AuditFacts.CountEvents:input_type -> audit.CountEventsRequest
	1, // 5: audit.AuditFacts.CountEvents:output_type -> audit.CountEventsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_audit_audit_proto_init() }
func file_audit_audit_proto_init() {
	if File_audit_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_audit_proto_goTypes,
		DependencyIndexes: file_audit_audit_proto_depIdxs,
		MessageInfos:      file_audit_audit_proto_msgTypes,
	}.Build()
	File_audit_audit_proto = out.File
	file_audit_audit_proto_goTypes = nil
	file_audit_audit_proto_depIdxs = nil
}
