// pkg/proto/couriers/couriers.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: couriers/couriers.proto

package couriers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CouriersService_UpdateCache_FullMethodName   = "/couriers.CouriersService/UpdateCache"
	CouriersService_GetUsersByIds_FullMethodName = "/couriers.CouriersService/GetUsersByIds"
)

// CouriersServiceClient is the client API for CouriersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouriersServiceClient interface {
	UpdateCache(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UpdateCacheResponse, error)
	GetUsersByIds(ctx context.Context, in *GetUsersByIdsRequest, opts ...grpc.CallOption) (*GetUsersByIdsResponse, error)
}

type couriersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCouriersServiceClient(cc grpc.ClientConnInterface) CouriersServiceClient {
	return &couriersServiceClient{cc}
}

func (c *couriersServiceClient) UpdateCache(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UpdateCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCacheResponse)
	err := c.cc.Invoke(ctx, CouriersService_UpdateCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couriersServiceClient) GetUsersByIds(ctx context.Context, in *GetUsersByIdsRequest, opts ...grpc.CallOption) (*GetUsersByIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersByIdsResponse)
	err := c.cc.Invoke(ctx, CouriersService_GetUsersByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouriersServiceServer is the server API for CouriersService service.
// All implementations must embed UnimplementedCouriersServiceServer
// for forward compatibility.
type CouriersServiceServer interface {
	UpdateCache(context.Context, *emptypb.Empty) (*UpdateCacheResponse, error)
	GetUsersByIds(context.Context, *GetUsersByIdsRequest) (*GetUsersByIdsResponse, error)
	mustEmbedUnimplementedCouriersServiceServer()
}

// UnimplementedCouriersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCouriersServiceServer struct{}

func (UnimplementedCouriersServiceServer) UpdateCache(context.Context, *emptypb.Empty) (*UpdateCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCache not implemented")
}
func (UnimplementedCouriersServiceServer) GetUsersByIds(context.Context, *GetUsersByIdsRequest) (*GetUsersByIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsersByIds not implemented")
}
func (UnimplementedCouriersServiceServer) mustEmbedUnimplementedCouriersServiceServer() {}
func (UnimplementedCouriersServiceServer) testEmbeddedByValue()                         {}

// UnsafeCouriersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouriersServiceServer will
// result in compilation errors.
type UnsafeCouriersServiceServer interface {
	mustEmbedUnimplementedCouriersServiceServer()
}

func RegisterCouriersServiceServer(s grpc.ServiceRegistrar, srv CouriersServiceServer) {
	// If the following call panics, it indicates UnimplementedCouriersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CouriersService_ServiceDesc, srv)
}

func _CouriersService_UpdateCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouriersServiceServer).UpdateCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouriersService_UpdateCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouriersServiceServer).UpdateCache(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouriersService_GetUsersByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouriersServiceServer).GetUsersByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouriersService_GetUsersByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouriersServiceServer).GetUsersByIds(ctx, req.(*GetUsersByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CouriersService_ServiceDesc is the grpc.ServiceDesc for CouriersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CouriersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "couriers.CouriersService",
	HandlerType: (*CouriersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCache",
			Handler:    _CouriersService_UpdateCache_Handler,
		},
		{
			MethodName: "GetUsersByIds",
			Handler:    _CouriersService_GetUsersByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "couriers/couriers.proto",
}
