// pkg/proto/couriers/couriers.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: couriers/couriers.proto

package couriers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCacheResponse) Reset() {
	*x = UpdateCacheResponse{}
	mi := &file_couriers_couriers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCacheResponse) ProtoMessage() {}

func (x *UpdateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCacheResponse.ProtoReflect.Descriptor instead.
func (*UpdateCacheResponse) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_couriers_couriers_proto protoreflect.FileDescriptor

const file_couriers_couriers_proto_rawDesc = "" +
	"\n" +
	"\x17couriers/couriers.proto\x12\bcouriers\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x13UpdateCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2W\n" +
	"\x0fCouriersService\x12D\n" +
	"\vUpdateCache\x12\x16.google.protobuf.Empty\x1a\x1d.couriers.UpdateCacheResponseB.Z,github.com/TMS360/backend-pkg/proto/couriersb\x06proto3"

var (
	file_couriers_couriers_proto_rawDescOnce sync.Once
	file_couriers_couriers_proto_rawDescData []byte
)

func file_couriers_couriers_proto_rawDescGZIP() []byte {
	file_couriers_couriers_proto_rawDescOnce.Do(func() {
		file_couriers_couriers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couriers_couriers_proto_rawDesc), len(file_couriers_couriers_proto_rawDesc)))
	})
	return file_couriers_couriers_proto_rawDescData
}

var file_couriers_couriers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_couriers_couriers_proto_goTypes = []any{
	(*UpdateCacheResponse)(nil), // 0: couriers.UpdateCacheResponse
	(*emptypb.Empty)(nil),       // 1: google.protobuf.Empty
}
var file_couriers_couriers_proto_depIdxs = []int32{
	1, // 0: couriers.CouriersService.UpdateCache:input_type -> google.protobuf.Empty
	0, // 1: couriers.CouriersService.UpdateCache:output_type -> couriers.UpdateCacheResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_couriers_couriers_proto_init() }
func file_couriers_couriers_proto_init() {
	if File_couriers_couriers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couriers_couriers_proto_rawDesc), len(file_couriers_couriers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couriers_couriers_proto_goTypes,
		DependencyIndexes: file_couriers_couriers_proto_depIdxs,
		MessageInfos:      file_couriers_couriers_proto_msgTypes,
	}.Build()
	File_couriers_couriers_proto = out.File
	file_couriers_couriers_proto_goTypes = nil
	file_couriers_couriers_proto_depIdxs = nil
}
