// pkg/proto/couriers/couriers.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: couriers/couriers.proto

package couriers

import (
	filters "github.com/TMS360/backend-pkg/proto/filters"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *filters.StringFilter  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         *filters.StringFilter  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *filters.StringFilter  `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          *filters.StringFilter  `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Search        *string                `protobuf:"bytes,5,opt,name=search,proto3,oneof" json:"search,omitempty"` // full-text search across name, email
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilter) Reset() {
	*x = UserFilter{}
	mi := &file_couriers_couriers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilter) ProtoMessage() {}

func (x *UserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilter.ProtoReflect.Descriptor instead.
func (*UserFilter) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{0}
}

func (x *UserFilter) GetName() *filters.StringFilter {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserFilter) GetEmail() *filters.StringFilter {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *UserFilter) GetPhone() *filters.StringFilter {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *UserFilter) GetRole() *filters.StringFilter {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UserFilter) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type UpdateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCacheResponse) Reset() {
	*x = UpdateCacheResponse{}
	mi := &file_couriers_couriers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCacheResponse) ProtoMessage() {}

func (x *UpdateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCacheResponse.ProtoReflect.Descriptor instead.
func (*UpdateCacheResponse) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUsersByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdsRequest) Reset() {
	*x = GetUsersByIdsRequest{}
	mi := &file_couriers_couriers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdsRequest) ProtoMessage() {}

func (x *GetUsersByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByIdsRequest) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersByIdsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdsResponse) Reset() {
	*x = GetUsersByIdsResponse{}
	mi := &file_couriers_couriers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdsResponse) ProtoMessage() {}

func (x *GetUsersByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByIdsResponse) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersByIdsResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_couriers_couriers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListOfficeUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfficeUsersRequest) Reset() {
	*x = ListOfficeUsersRequest{}
	mi := &file_couriers_couriers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfficeUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficeUsersRequest) ProtoMessage() {}

func (x *ListOfficeUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficeUsersRequest.ProtoReflect.Descriptor instead.
func (*ListOfficeUsersRequest) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{5}
}

func (x *ListOfficeUsersRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ListOfficeUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfficeUsersResponse) Reset() {
	*x = ListOfficeUsersResponse{}
	mi := &file_couriers_couriers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfficeUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficeUsersResponse) ProtoMessage() {}

func (x *ListOfficeUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficeUsersResponse.ProtoReflect.Descriptor instead.
func (*ListOfficeUsersResponse) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{6}
}

func (x *ListOfficeUsersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ListUserFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entity_type ∈ {"DRIVER", "DISPATCHER"}
	EntityType    string `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserFilesRequest) Reset() {
	*x = ListUserFilesRequest{}
	mi := &file_couriers_couriers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFilesRequest) ProtoMessage() {}

func (x *ListUserFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFilesRequest.ProtoReflect.Descriptor instead.
func (*ListUserFilesRequest) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserFilesRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ListUserFilesRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type UserFile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType     string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId       string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FileId         string                 `protobuf:"bytes,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	DocumentType   string                 `protobuf:"bytes,5,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentTypeId string                 `protobuf:"bytes,6,opt,name=document_type_id,json=documentTypeId,proto3" json:"document_type_id,omitempty"`
	CompanyId      string                 `protobuf:"bytes,7,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	UploadedBy     string                 `protobuf:"bytes,8,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	Notes          string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	// RFC3339 timestamps
	CreatedAt     string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFile) Reset() {
	*x = UserFile{}
	mi := &file_couriers_couriers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFile) ProtoMessage() {}

func (x *UserFile) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFile.ProtoReflect.Descriptor instead.
func (*UserFile) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{8}
}

func (x *UserFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserFile) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *UserFile) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *UserFile) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UserFile) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *UserFile) GetDocumentTypeId() string {
	if x != nil {
		return x.DocumentTypeId
	}
	return ""
}

func (x *UserFile) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UserFile) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *UserFile) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UserFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserFile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListUserFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*UserFile            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserFilesResponse) Reset() {
	*x = ListUserFilesResponse{}
	mi := &file_couriers_couriers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserFilesResponse) ProtoMessage() {}

func (x *ListUserFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couriers_couriers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserFilesResponse.ProtoReflect.Descriptor instead.
func (*ListUserFilesResponse) Descriptor() ([]byte, []int) {
	return file_couriers_couriers_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserFilesResponse) GetFiles() []*UserFile {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_couriers_couriers_proto protoreflect.FileDescriptor

const file_couriers_couriers_proto_rawDesc = "" +
	"\n" +
	"\x17couriers/couriers.proto\x12\bcouriers\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15filters/filters.proto\"\xe4\x01\n" +
	"\n" +
	"UserFilter\x12)\n" +
	"\x04name\x18\x01 \x01(\v2\x15.filters.StringFilterR\x04name\x12+\n" +
	"\x05email\x18\x02 \x01(\v2\x15.filters.StringFilterR\x05email\x12+\n" +
	"\x05phone\x18\x03 \x01(\v2\x15.filters.StringFilterR\x05phone\x12)\n" +
	"\x04role\x18\x04 \x01(\v2\x15.filters.StringFilterR\x04role\x12\x1b\n" +
	"\x06search\x18\x05 \x01(\tH\x00R\x06search\x88\x01\x01B\t\n" +
	"\a_search\"/\n" +
	"\x13UpdateCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x14GetUsersByIdsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"A\n" +
	"\x15GetUsersByIdsResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.couriers.UserInfoR\x05users\"D\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"7\n" +
	"\x16ListOfficeUsersRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"4\n" +
	"\x17ListOfficeUsersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"T\n" +
	"\x14ListUserFilesRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\"\xd4\x02\n" +
	"\bUserFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x17\n" +
	"\afile_id\x18\x04 \x01(\tR\x06fileId\x12#\n" +
	"\rdocument_type\x18\x05 \x01(\tR\fdocumentType\x12(\n" +
	"\x10document_type_id\x18\x06 \x01(\tR\x0edocumentTypeId\x12\x1d\n" +
	"\n" +
	"company_id\x18\a \x01(\tR\tcompanyId\x12\x1f\n" +
	"\vuploaded_by\x18\b \x01(\tR\n" +
	"uploadedBy\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"A\n" +
	"\x15ListUserFilesResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.couriers.UserFileR\x05files2\x8d\x03\n" +
	"\x0fCouriersService\x12D\n" +
	"\vUpdateCache\x12\x16.google.protobuf.Empty\x1a\x1d.couriers.UpdateCacheResponse\x12P\n" +
	"\rGetUsersByIds\x12\x1e.couriers.GetUsersByIdsRequest\x1a\x1f.couriers.GetUsersByIdsResponse\x128\n" +
	"\n" +
	"ResolveIDs\x12\x14.couriers.UserFilter\x1a\x14.filters.IDsResponse\x12V\n" +
	"\x0fListOfficeUsers\x12 .couriers.ListOfficeUsersRequest\x1a!.couriers.ListOfficeUsersResponse\x12P\n" +
	"\rListUserFiles\x12\x1e.couriers.ListUserFilesRequest\x1a\x1f.couriers.ListUserFilesResponseB.Z,github.com/TMS360/backend-pkg/proto/couriersb\x06proto3"

var (
	file_couriers_couriers_proto_rawDescOnce sync.Once
	file_couriers_couriers_proto_rawDescData []byte
)

func file_couriers_couriers_proto_rawDescGZIP() []byte {
	file_couriers_couriers_proto_rawDescOnce.Do(func() {
		file_couriers_couriers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couriers_couriers_proto_rawDesc), len(file_couriers_couriers_proto_rawDesc)))
	})
	return file_couriers_couriers_proto_rawDescData
}

var file_couriers_couriers_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_couriers_couriers_proto_goTypes = []any{
	(*UserFilter)(nil),              // 0: couriers.UserFilter
	(*UpdateCacheResponse)(nil),     // 1: couriers.UpdateCacheResponse
	(*GetUsersByIdsRequest)(nil),    // 2: couriers.GetUsersByIdsRequest
	(*GetUsersByIdsResponse)(nil),   // 3: couriers.GetUsersByIdsResponse
	(*UserInfo)(nil),                // 4: couriers.UserInfo
	(*ListOfficeUsersRequest)(nil),  // 5: couriers.ListOfficeUsersRequest
	(*ListOfficeUsersResponse)(nil), // 6: couriers.ListOfficeUsersResponse
	(*ListUserFilesRequest)(nil),    // 7: couriers.ListUserFilesRequest
	(*UserFile)(nil),                // 8: couriers.UserFile
	(*ListUserFilesResponse)(nil),   // 9: couriers.ListUserFilesResponse
	(*filters.StringFilter)(nil),    // 10: filters.StringFilter
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
	(*filters.IDsResponse)(nil),     // 12: filters.IDsResponse
}
var file_couriers_couriers_proto_depIdxs = []int32{
	10, // 0: couriers.UserFilter.name:type_name -> filters.StringFilter
	10, // 1: couriers.UserFilter.email:type_name -> filters.StringFilter
	10, // 2: couriers.UserFilter.phone:type_name -> filters.StringFilter
	10, // 3: couriers.UserFilter.role:type_name -> filters.StringFilter
	4,  // 4: couriers.GetUsersByIdsResponse.users:type_name -> couriers.UserInfo
	8,  // 5: couriers.ListUserFilesResponse.files:type_name -> couriers.UserFile
	11, // 6: couriers.CouriersService.UpdateCache:input_type -> google.protobuf.Empty
	2,  // 7: couriers.CouriersService.GetUsersByIds:input_type -> couriers.GetUsersByIdsRequest
	0,  // 8: couriers.CouriersService.ResolveIDs:input_type -> couriers.UserFilter
	5,  // 9: couriers.CouriersService.ListOfficeUsers:input_type -> couriers.ListOfficeUsersRequest
	7,  // 10: couriers.CouriersService.ListUserFiles:input_type -> couriers.ListUserFilesRequest
	1,  // 11: couriers.CouriersService.UpdateCache:output_type -> couriers.UpdateCacheResponse
	3,  // 12: couriers.CouriersService.GetUsersByIds:output_type -> couriers.GetUsersByIdsResponse
	12, // 13: couriers.CouriersService.ResolveIDs:output_type -> filters.IDsResponse
	6,  // 14: couriers.CouriersService.ListOfficeUsers:output_type -> couriers.ListOfficeUsersResponse
	9,  // 15: couriers.CouriersService.ListUserFiles:output_type -> couriers.ListUserFilesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_couriers_couriers_proto_init() }
func file_couriers_couriers_proto_init() {
	if File_couriers_couriers_proto != nil {
		return
	}
	file_couriers_couriers_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couriers_couriers_proto_rawDesc), len(file_couriers_couriers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couriers_couriers_proto_goTypes,
		DependencyIndexes: file_couriers_couriers_proto_depIdxs,
		MessageInfos:      file_couriers_couriers_proto_msgTypes,
	}.Build()
	File_couriers_couriers_proto = out.File
	file_couriers_couriers_proto_goTypes = nil
	file_couriers_couriers_proto_depIdxs = nil
}
