// pkg/proto/brokers/brokers.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: brokers/brokers.proto

package brokers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrCreateByMCRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	McNumber string                 `protobuf:"bytes,1,opt,name=mc_number,json=mcNumber,proto3" json:"mc_number,omitempty"`
	// Useful for audit logs: "Created via Courier App by Courier <UUID>"
	CreatedBySource string `protobuf:"bytes,2,opt,name=created_by_source,json=createdBySource,proto3" json:"created_by_source,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrCreateByMCRequest) Reset() {
	*x = GetOrCreateByMCRequest{}
	mi := &file_brokers_brokers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateByMCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateByMCRequest) ProtoMessage() {}

func (x *GetOrCreateByMCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brokers_brokers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateByMCRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateByMCRequest) Descriptor() ([]byte, []int) {
	return file_brokers_brokers_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrCreateByMCRequest) GetMcNumber() string {
	if x != nil {
		return x.McNumber
	}
	return ""
}

func (x *GetOrCreateByMCRequest) GetCreatedBySource() string {
	if x != nil {
		return x.CreatedBySource
	}
	return ""
}

type Broker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	CompanyName   string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	McNumber      string                 `protobuf:"bytes,3,opt,name=mc_number,json=mcNumber,proto3" json:"mc_number,omitempty"`
	DotNumber     string                 `protobuf:"bytes,4,opt,name=dot_number,json=dotNumber,proto3" json:"dot_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broker) Reset() {
	*x = Broker{}
	mi := &file_brokers_brokers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broker) ProtoMessage() {}

func (x *Broker) ProtoReflect() protoreflect.Message {
	mi := &file_brokers_brokers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broker.ProtoReflect.Descriptor instead.
func (*Broker) Descriptor() ([]byte, []int) {
	return file_brokers_brokers_proto_rawDescGZIP(), []int{1}
}

func (x *Broker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Broker) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Broker) GetMcNumber() string {
	if x != nil {
		return x.McNumber
	}
	return ""
}

func (x *Broker) GetDotNumber() string {
	if x != nil {
		return x.DotNumber
	}
	return ""
}

type GetOrCreateByMCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"` // UUID
	WasCreated    bool                   `protobuf:"varint,2,opt,name=was_created,json=wasCreated,proto3" json:"was_created,omitempty"`
	Broker        *Broker                `protobuf:"bytes,3,opt,name=broker,proto3" json:"broker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateByMCResponse) Reset() {
	*x = GetOrCreateByMCResponse{}
	mi := &file_brokers_brokers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateByMCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateByMCResponse) ProtoMessage() {}

func (x *GetOrCreateByMCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brokers_brokers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateByMCResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateByMCResponse) Descriptor() ([]byte, []int) {
	return file_brokers_brokers_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrCreateByMCResponse) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *GetOrCreateByMCResponse) GetWasCreated() bool {
	if x != nil {
		return x.WasCreated
	}
	return false
}

func (x *GetOrCreateByMCResponse) GetBroker() *Broker {
	if x != nil {
		return x.Broker
	}
	return nil
}

var File_brokers_brokers_proto protoreflect.FileDescriptor

const file_brokers_brokers_proto_rawDesc = "" +
	"\n" +
	"\x15brokers/brokers.proto\x12\abrokers\"a\n" +
	"\x16GetOrCreateByMCRequest\x12\x1b\n" +
	"\tmc_number\x18\x01 \x01(\tR\bmcNumber\x12*\n" +
	"\x11created_by_source\x18\x02 \x01(\tR\x0fcreatedBySource\"w\n" +
	"\x06Broker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12\x1b\n" +
	"\tmc_number\x18\x03 \x01(\tR\bmcNumber\x12\x1d\n" +
	"\n" +
	"dot_number\x18\x04 \x01(\tR\tdotNumber\"\x80\x01\n" +
	"\x17GetOrCreateByMCResponse\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\x12\x1f\n" +
	"\vwas_created\x18\x02 \x01(\bR\n" +
	"wasCreated\x12'\n" +
	"\x06broker\x18\x03 \x01(\v2\x0f.brokers.BrokerR\x06broker2e\n" +
	"\rBrokerService\x12T\n" +
	"\x0fGetOrCreateByMC\x12\x1f.brokers.GetOrCreateByMCRequest\x1a .brokers.GetOrCreateByMCResponseB-Z+github.com/TMS360/backend-pkg/proto/brokersb\x06proto3"

var (
	file_brokers_brokers_proto_rawDescOnce sync.Once
	file_brokers_brokers_proto_rawDescData []byte
)

func file_brokers_brokers_proto_rawDescGZIP() []byte {
	file_brokers_brokers_proto_rawDescOnce.Do(func() {
		file_brokers_brokers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brokers_brokers_proto_rawDesc), len(file_brokers_brokers_proto_rawDesc)))
	})
	return file_brokers_brokers_proto_rawDescData
}

var file_brokers_brokers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_brokers_brokers_proto_goTypes = []any{
	(*GetOrCreateByMCRequest)(nil),  // 0: brokers.GetOrCreateByMCRequest
	(*Broker)(nil),                  // 1: brokers.Broker
	(*GetOrCreateByMCResponse)(nil), // 2: brokers.GetOrCreateByMCResponse
}
var file_brokers_brokers_proto_depIdxs = []int32{
	1, // 0: brokers.GetOrCreateByMCResponse.broker:type_name -> brokers.Broker
	0, // 1: brokers.BrokerService.GetOrCreateByMC:input_type -> brokers.GetOrCreateByMCRequest
	2, // 2: brokers.BrokerService.GetOrCreateByMC:output_type -> brokers.GetOrCreateByMCResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_brokers_brokers_proto_init() }
func file_brokers_brokers_proto_init() {
	if File_brokers_brokers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brokers_brokers_proto_rawDesc), len(file_brokers_brokers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brokers_brokers_proto_goTypes,
		DependencyIndexes: file_brokers_brokers_proto_depIdxs,
		MessageInfos:      file_brokers_brokers_proto_msgTypes,
	}.Build()
	File_brokers_brokers_proto = out.File
	file_brokers_brokers_proto_goTypes = nil
	file_brokers_brokers_proto_depIdxs = nil
}
