// pkg/proto/teams/teams.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: teams/teams.proto

package teams

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GerCurrentDriversBuTruckIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckIds      []string               `protobuf:"bytes,1,rep,name=truck_ids,json=truckIds,proto3" json:"truck_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GerCurrentDriversBuTruckIDRequest) Reset() {
	*x = GerCurrentDriversBuTruckIDRequest{}
	mi := &file_teams_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GerCurrentDriversBuTruckIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GerCurrentDriversBuTruckIDRequest) ProtoMessage() {}

func (x *GerCurrentDriversBuTruckIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GerCurrentDriversBuTruckIDRequest.ProtoReflect.Descriptor instead.
func (*GerCurrentDriversBuTruckIDRequest) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{0}
}

func (x *GerCurrentDriversBuTruckIDRequest) GetTruckIds() []string {
	if x != nil {
		return x.TruckIds
	}
	return nil
}

type GerCurrentDriversBuTruckIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckId       []string               `protobuf:"bytes,1,rep,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	FirstDriver   []string               `protobuf:"bytes,2,rep,name=first_driver,json=firstDriver,proto3" json:"first_driver,omitempty"`
	SecondDriver  []string               `protobuf:"bytes,3,rep,name=second_driver,json=secondDriver,proto3" json:"second_driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GerCurrentDriversBuTruckIDResponse) Reset() {
	*x = GerCurrentDriversBuTruckIDResponse{}
	mi := &file_teams_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GerCurrentDriversBuTruckIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GerCurrentDriversBuTruckIDResponse) ProtoMessage() {}

func (x *GerCurrentDriversBuTruckIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GerCurrentDriversBuTruckIDResponse.ProtoReflect.Descriptor instead.
func (*GerCurrentDriversBuTruckIDResponse) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{1}
}

func (x *GerCurrentDriversBuTruckIDResponse) GetTruckId() []string {
	if x != nil {
		return x.TruckId
	}
	return nil
}

func (x *GerCurrentDriversBuTruckIDResponse) GetFirstDriver() []string {
	if x != nil {
		return x.FirstDriver
	}
	return nil
}

func (x *GerCurrentDriversBuTruckIDResponse) GetSecondDriver() []string {
	if x != nil {
		return x.SecondDriver
	}
	return nil
}

type GetBusyVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusyVehiclesRequest) Reset() {
	*x = GetBusyVehiclesRequest{}
	mi := &file_teams_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusyVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusyVehiclesRequest) ProtoMessage() {}

func (x *GetBusyVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusyVehiclesRequest.ProtoReflect.Descriptor instead.
func (*GetBusyVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{2}
}

func (x *GetBusyVehiclesRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetBusyVehiclesRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetBusyVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckIds      []string               `protobuf:"bytes,1,rep,name=truck_ids,json=truckIds,proto3" json:"truck_ids,omitempty"`
	TrailerIds    []string               `protobuf:"bytes,2,rep,name=trailer_ids,json=trailerIds,proto3" json:"trailer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusyVehiclesResponse) Reset() {
	*x = GetBusyVehiclesResponse{}
	mi := &file_teams_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusyVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusyVehiclesResponse) ProtoMessage() {}

func (x *GetBusyVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusyVehiclesResponse.ProtoReflect.Descriptor instead.
func (*GetBusyVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{3}
}

func (x *GetBusyVehiclesResponse) GetTruckIds() []string {
	if x != nil {
		return x.TruckIds
	}
	return nil
}

func (x *GetBusyVehiclesResponse) GetTrailerIds() []string {
	if x != nil {
		return x.TrailerIds
	}
	return nil
}

var File_teams_teams_proto protoreflect.FileDescriptor

const file_teams_teams_proto_rawDesc = "" +
	"\n" +
	"\x11teams/teams.proto\x12\x05teams\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"!GerCurrentDriversBuTruckIDRequest\x12\x1b\n" +
	"\ttruck_ids\x18\x01 \x03(\tR\btruckIds\"\x87\x01\n" +
	"\"GerCurrentDriversBuTruckIDResponse\x12\x19\n" +
	"\btruck_id\x18\x01 \x03(\tR\atruckId\x12!\n" +
	"\ffirst_driver\x18\x02 \x03(\tR\vfirstDriver\x12#\n" +
	"\rsecond_driver\x18\x03 \x03(\tR\fsecondDriver\"t\n" +
	"\x16GetBusyVehiclesRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"W\n" +
	"\x17GetBusyVehiclesResponse\x12\x1b\n" +
	"\ttruck_ids\x18\x01 \x03(\tR\btruckIds\x12\x1f\n" +
	"\vtrailer_ids\x18\x02 \x03(\tR\n" +
	"trailerIds2\xca\x01\n" +
	"\fTeamsService\x12P\n" +
	"\x0fGetBusyVehicles\x12\x1d.teams.GetBusyVehiclesRequest\x1a\x1e.teams.GetBusyVehiclesResponse\x12h\n" +
	"\x11GerCurrentDrivers\x12(.teams.GerCurrentDriversBuTruckIDRequest\x1a).teams.GerCurrentDriversBuTruckIDResponseB+Z)github.com/TMS360/backend-pkg/proto/teamsb\x06proto3"

var (
	file_teams_teams_proto_rawDescOnce sync.Once
	file_teams_teams_proto_rawDescData []byte
)

func file_teams_teams_proto_rawDescGZIP() []byte {
	file_teams_teams_proto_rawDescOnce.Do(func() {
		file_teams_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teams_teams_proto_rawDesc), len(file_teams_teams_proto_rawDesc)))
	})
	return file_teams_teams_proto_rawDescData
}

var file_teams_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_teams_teams_proto_goTypes = []any{
	(*GerCurrentDriversBuTruckIDRequest)(nil),  // 0: teams.GerCurrentDriversBuTruckIDRequest
	(*GerCurrentDriversBuTruckIDResponse)(nil), // 1: teams.GerCurrentDriversBuTruckIDResponse
	(*GetBusyVehiclesRequest)(nil),             // 2: teams.GetBusyVehiclesRequest
	(*GetBusyVehiclesResponse)(nil),            // 3: teams.GetBusyVehiclesResponse
	(*timestamppb.Timestamp)(nil),              // 4: google.protobuf.Timestamp
}
var file_teams_teams_proto_depIdxs = []int32{
	4, // 0: teams.GetBusyVehiclesRequest.from:type_name -> google.protobuf.Timestamp
	4, // 1: teams.GetBusyVehiclesRequest.to:type_name -> google.protobuf.Timestamp
	2, // 2: teams.TeamsService.GetBusyVehicles:input_type -> teams.GetBusyVehiclesRequest
	0, // 3: teams.TeamsService.GerCurrentDrivers:input_type -> teams.GerCurrentDriversBuTruckIDRequest
	3, // 4: teams.TeamsService.GetBusyVehicles:output_type -> teams.GetBusyVehiclesResponse
	1, // 5: teams.TeamsService.GerCurrentDrivers:output_type -> teams.GerCurrentDriversBuTruckIDResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_teams_teams_proto_init() }
func file_teams_teams_proto_init() {
	if File_teams_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teams_teams_proto_rawDesc), len(file_teams_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teams_teams_proto_goTypes,
		DependencyIndexes: file_teams_teams_proto_depIdxs,
		MessageInfos:      file_teams_teams_proto_msgTypes,
	}.Build()
	File_teams_teams_proto = out.File
	file_teams_teams_proto_goTypes = nil
	file_teams_teams_proto_depIdxs = nil
}
