// pkg/proto/teams/teams.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: teams/teams.proto

package teams

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBusyVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusyVehiclesRequest) Reset() {
	*x = GetBusyVehiclesRequest{}
	mi := &file_teams_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusyVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusyVehiclesRequest) ProtoMessage() {}

func (x *GetBusyVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusyVehiclesRequest.ProtoReflect.Descriptor instead.
func (*GetBusyVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{0}
}

func (x *GetBusyVehiclesRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetBusyVehiclesRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetBusyVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckIds      []string               `protobuf:"bytes,1,rep,name=truck_ids,json=truckIds,proto3" json:"truck_ids,omitempty"`
	TrailerIds    []string               `protobuf:"bytes,2,rep,name=trailer_ids,json=trailerIds,proto3" json:"trailer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusyVehiclesResponse) Reset() {
	*x = GetBusyVehiclesResponse{}
	mi := &file_teams_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusyVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusyVehiclesResponse) ProtoMessage() {}

func (x *GetBusyVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusyVehiclesResponse.ProtoReflect.Descriptor instead.
func (*GetBusyVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{1}
}

func (x *GetBusyVehiclesResponse) GetTruckIds() []string {
	if x != nil {
		return x.TruckIds
	}
	return nil
}

func (x *GetBusyVehiclesResponse) GetTrailerIds() []string {
	if x != nil {
		return x.TrailerIds
	}
	return nil
}

type GetCurrentDriversByTruckIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckIds      []string               `protobuf:"bytes,1,rep,name=truck_ids,json=truckIds,proto3" json:"truck_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentDriversByTruckIdsRequest) Reset() {
	*x = GetCurrentDriversByTruckIdsRequest{}
	mi := &file_teams_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentDriversByTruckIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentDriversByTruckIdsRequest) ProtoMessage() {}

func (x *GetCurrentDriversByTruckIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentDriversByTruckIdsRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentDriversByTruckIdsRequest) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{2}
}

func (x *GetCurrentDriversByTruckIdsRequest) GetTruckIds() []string {
	if x != nil {
		return x.TruckIds
	}
	return nil
}

type GetCurrentDriversByTruckIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DriverInfo          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentDriversByTruckIdsResponse) Reset() {
	*x = GetCurrentDriversByTruckIdsResponse{}
	mi := &file_teams_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentDriversByTruckIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentDriversByTruckIdsResponse) ProtoMessage() {}

func (x *GetCurrentDriversByTruckIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentDriversByTruckIdsResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentDriversByTruckIdsResponse) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentDriversByTruckIdsResponse) GetData() []*DriverInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCurrentDriversByTrailerIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrailerIds    []string               `protobuf:"bytes,1,rep,name=trailer_ids,json=trailerIds,proto3" json:"trailer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentDriversByTrailerIdsRequest) Reset() {
	*x = GetCurrentDriversByTrailerIdsRequest{}
	mi := &file_teams_teams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentDriversByTrailerIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentDriversByTrailerIdsRequest) ProtoMessage() {}

func (x *GetCurrentDriversByTrailerIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentDriversByTrailerIdsRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentDriversByTrailerIdsRequest) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrentDriversByTrailerIdsRequest) GetTrailerIds() []string {
	if x != nil {
		return x.TrailerIds
	}
	return nil
}

type GetCurrentDriversByTrailerIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TrailerInfo         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentDriversByTrailerIdsResponse) Reset() {
	*x = GetCurrentDriversByTrailerIdsResponse{}
	mi := &file_teams_teams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentDriversByTrailerIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentDriversByTrailerIdsResponse) ProtoMessage() {}

func (x *GetCurrentDriversByTrailerIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentDriversByTrailerIdsResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentDriversByTrailerIdsResponse) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrentDriversByTrailerIdsResponse) GetData() []*TrailerInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type DriverInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PrimaryDriverId   string                 `protobuf:"bytes,1,opt,name=primary_driver_id,json=primaryDriverId,proto3" json:"primary_driver_id,omitempty"`
	SecondaryDriverId string                 `protobuf:"bytes,2,opt,name=secondary_driver_id,json=secondaryDriverId,proto3" json:"secondary_driver_id,omitempty"`
	TruckId           string                 `protobuf:"bytes,3,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	TrailerId         string                 `protobuf:"bytes,4,opt,name=trailer_id,json=trailerId,proto3" json:"trailer_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	mi := &file_teams_teams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{6}
}

func (x *DriverInfo) GetPrimaryDriverId() string {
	if x != nil {
		return x.PrimaryDriverId
	}
	return ""
}

func (x *DriverInfo) GetSecondaryDriverId() string {
	if x != nil {
		return x.SecondaryDriverId
	}
	return ""
}

func (x *DriverInfo) GetTruckId() string {
	if x != nil {
		return x.TruckId
	}
	return ""
}

func (x *DriverInfo) GetTrailerId() string {
	if x != nil {
		return x.TrailerId
	}
	return ""
}

type TrailerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckId       string                 `protobuf:"bytes,1,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrailerInfo) Reset() {
	*x = TrailerInfo{}
	mi := &file_teams_teams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrailerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrailerInfo) ProtoMessage() {}

func (x *TrailerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_teams_teams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrailerInfo.ProtoReflect.Descriptor instead.
func (*TrailerInfo) Descriptor() ([]byte, []int) {
	return file_teams_teams_proto_rawDescGZIP(), []int{7}
}

func (x *TrailerInfo) GetTruckId() string {
	if x != nil {
		return x.TruckId
	}
	return ""
}

var File_teams_teams_proto protoreflect.FileDescriptor

const file_teams_teams_proto_rawDesc = "" +
	"\n" +
	"\x11teams/teams.proto\x12\x05teams\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n" +
	"\x16GetBusyVehiclesRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"W\n" +
	"\x17GetBusyVehiclesResponse\x12\x1b\n" +
	"\ttruck_ids\x18\x01 \x03(\tR\btruckIds\x12\x1f\n" +
	"\vtrailer_ids\x18\x02 \x03(\tR\n" +
	"trailerIds\"A\n" +
	"\"GetCurrentDriversByTruckIdsRequest\x12\x1b\n" +
	"\ttruck_ids\x18\x01 \x03(\tR\btruckIds\"L\n" +
	"#GetCurrentDriversByTruckIdsResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.teams.DriverInfoR\x04data\"G\n" +
	"$GetCurrentDriversByTrailerIdsRequest\x12\x1f\n" +
	"\vtrailer_ids\x18\x01 \x03(\tR\n" +
	"trailerIds\"O\n" +
	"%GetCurrentDriversByTrailerIdsResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.teams.TrailerInfoR\x04data\"\xa2\x01\n" +
	"\n" +
	"DriverInfo\x12*\n" +
	"\x11primary_driver_id\x18\x01 \x01(\tR\x0fprimaryDriverId\x12.\n" +
	"\x13secondary_driver_id\x18\x02 \x01(\tR\x11secondaryDriverId\x12\x19\n" +
	"\btruck_id\x18\x03 \x01(\tR\atruckId\x12\x1d\n" +
	"\n" +
	"trailer_id\x18\x04 \x01(\tR\ttrailerId\"(\n" +
	"\vTrailerInfo\x12\x19\n" +
	"\btruck_id\x18\x01 \x01(\tR\atruckId2\xd2\x02\n" +
	"\fTeamsService\x12P\n" +
	"\x0fGetBusyVehicles\x12\x1d.teams.GetBusyVehiclesRequest\x1a\x1e.teams.GetBusyVehiclesResponse\x12t\n" +
	"\x1bGetCurrentDriversByTruckIds\x12).teams.GetCurrentDriversByTruckIdsRequest\x1a*.teams.GetCurrentDriversByTruckIdsResponse\x12z\n" +
	"\x1dGetCurrentDriversByTrailerIds\x12+.teams.GetCurrentDriversByTrailerIdsRequest\x1a,.teams.GetCurrentDriversByTrailerIdsResponseB+Z)github.com/TMS360/backend-pkg/proto/teamsb\x06proto3"

var (
	file_teams_teams_proto_rawDescOnce sync.Once
	file_teams_teams_proto_rawDescData []byte
)

func file_teams_teams_proto_rawDescGZIP() []byte {
	file_teams_teams_proto_rawDescOnce.Do(func() {
		file_teams_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teams_teams_proto_rawDesc), len(file_teams_teams_proto_rawDesc)))
	})
	return file_teams_teams_proto_rawDescData
}

var file_teams_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_teams_teams_proto_goTypes = []any{
	(*GetBusyVehiclesRequest)(nil),                // 0: teams.GetBusyVehiclesRequest
	(*GetBusyVehiclesResponse)(nil),               // 1: teams.GetBusyVehiclesResponse
	(*GetCurrentDriversByTruckIdsRequest)(nil),    // 2: teams.GetCurrentDriversByTruckIdsRequest
	(*GetCurrentDriversByTruckIdsResponse)(nil),   // 3: teams.GetCurrentDriversByTruckIdsResponse
	(*GetCurrentDriversByTrailerIdsRequest)(nil),  // 4: teams.GetCurrentDriversByTrailerIdsRequest
	(*GetCurrentDriversByTrailerIdsResponse)(nil), // 5: teams.GetCurrentDriversByTrailerIdsResponse
	(*DriverInfo)(nil),                            // 6: teams.DriverInfo
	(*TrailerInfo)(nil),                           // 7: teams.TrailerInfo
	(*timestamppb.Timestamp)(nil),                 // 8: google.protobuf.Timestamp
}
var file_teams_teams_proto_depIdxs = []int32{
	8, // 0: teams.GetBusyVehiclesRequest.from:type_name -> google.protobuf.Timestamp
	8, // 1: teams.GetBusyVehiclesRequest.to:type_name -> google.protobuf.Timestamp
	6, // 2: teams.GetCurrentDriversByTruckIdsResponse.data:type_name -> teams.DriverInfo
	7, // 3: teams.GetCurrentDriversByTrailerIdsResponse.data:type_name -> teams.TrailerInfo
	0, // 4: teams.TeamsService.GetBusyVehicles:input_type -> teams.GetBusyVehiclesRequest
	2, // 5: teams.TeamsService.GetCurrentDriversByTruckIds:input_type -> teams.GetCurrentDriversByTruckIdsRequest
	4, // 6: teams.TeamsService.GetCurrentDriversByTrailerIds:input_type -> teams.GetCurrentDriversByTrailerIdsRequest
	1, // 7: teams.TeamsService.GetBusyVehicles:output_type -> teams.GetBusyVehiclesResponse
	3, // 8: teams.TeamsService.GetCurrentDriversByTruckIds:output_type -> teams.GetCurrentDriversByTruckIdsResponse
	5, // 9: teams.TeamsService.GetCurrentDriversByTrailerIds:output_type -> teams.GetCurrentDriversByTrailerIdsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_teams_teams_proto_init() }
func file_teams_teams_proto_init() {
	if File_teams_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teams_teams_proto_rawDesc), len(file_teams_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teams_teams_proto_goTypes,
		DependencyIndexes: file_teams_teams_proto_depIdxs,
		MessageInfos:      file_teams_teams_proto_msgTypes,
	}.Build()
	File_teams_teams_proto = out.File
	file_teams_teams_proto_goTypes = nil
	file_teams_teams_proto_depIdxs = nil
}
