// pkg/proto/teams/teams.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: teams/teams.proto

package teams

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeamsService_GetDriverCrew_FullMethodName                 = "/teams.TeamsService/GetDriverCrew"
	TeamsService_GetDriverCrewWithDispatchers_FullMethodName  = "/teams.TeamsService/GetDriverCrewWithDispatchers"
	TeamsService_GetBusyVehicles_FullMethodName               = "/teams.TeamsService/GetBusyVehicles"
	TeamsService_GetCurrentDriversByTruckIds_FullMethodName   = "/teams.TeamsService/GetCurrentDriversByTruckIds"
	TeamsService_GetCurrentDriversByTrailerIds_FullMethodName = "/teams.TeamsService/GetCurrentDriversByTrailerIds"
)

// TeamsServiceClient is the client API for TeamsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamsServiceClient interface {
	// Get DriverCrew details by targetDate
	GetDriverCrew(ctx context.Context, in *GetDriverCrewRequest, opts ...grpc.CallOption) (*GetDriverCrewResponse, error)
	GetDriverCrewWithDispatchers(ctx context.Context, in *GetDriverCrewRequest, opts ...grpc.CallOption) (*GetDriverCrewWithDispatchersResponse, error)
	// Returns IDs of vehicles assigned during the requested window
	GetBusyVehicles(ctx context.Context, in *GetBusyVehiclesRequest, opts ...grpc.CallOption) (*GetBusyVehiclesResponse, error)
	// Get current drivers for a list of trucks
	GetCurrentDriversByTruckIds(ctx context.Context, in *GetCurrentDriversByTruckIdsRequest, opts ...grpc.CallOption) (*GetCurrentDriversByTruckIdsResponse, error)
	GetCurrentDriversByTrailerIds(ctx context.Context, in *GetCurrentDriversByTrailerIdsRequest, opts ...grpc.CallOption) (*GetCurrentDriversByTrailerIdsResponse, error)
}

type teamsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamsServiceClient(cc grpc.ClientConnInterface) TeamsServiceClient {
	return &teamsServiceClient{cc}
}

func (c *teamsServiceClient) GetDriverCrew(ctx context.Context, in *GetDriverCrewRequest, opts ...grpc.CallOption) (*GetDriverCrewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverCrewResponse)
	err := c.cc.Invoke(ctx, TeamsService_GetDriverCrew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsServiceClient) GetDriverCrewWithDispatchers(ctx context.Context, in *GetDriverCrewRequest, opts ...grpc.CallOption) (*GetDriverCrewWithDispatchersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverCrewWithDispatchersResponse)
	err := c.cc.Invoke(ctx, TeamsService_GetDriverCrewWithDispatchers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsServiceClient) GetBusyVehicles(ctx context.Context, in *GetBusyVehiclesRequest, opts ...grpc.CallOption) (*GetBusyVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusyVehiclesResponse)
	err := c.cc.Invoke(ctx, TeamsService_GetBusyVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsServiceClient) GetCurrentDriversByTruckIds(ctx context.Context, in *GetCurrentDriversByTruckIdsRequest, opts ...grpc.CallOption) (*GetCurrentDriversByTruckIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentDriversByTruckIdsResponse)
	err := c.cc.Invoke(ctx, TeamsService_GetCurrentDriversByTruckIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamsServiceClient) GetCurrentDriversByTrailerIds(ctx context.Context, in *GetCurrentDriversByTrailerIdsRequest, opts ...grpc.CallOption) (*GetCurrentDriversByTrailerIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentDriversByTrailerIdsResponse)
	err := c.cc.Invoke(ctx, TeamsService_GetCurrentDriversByTrailerIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamsServiceServer is the server API for TeamsService service.
// All implementations must embed UnimplementedTeamsServiceServer
// for forward compatibility.
type TeamsServiceServer interface {
	// Get DriverCrew details by targetDate
	GetDriverCrew(context.Context, *GetDriverCrewRequest) (*GetDriverCrewResponse, error)
	GetDriverCrewWithDispatchers(context.Context, *GetDriverCrewRequest) (*GetDriverCrewWithDispatchersResponse, error)
	// Returns IDs of vehicles assigned during the requested window
	GetBusyVehicles(context.Context, *GetBusyVehiclesRequest) (*GetBusyVehiclesResponse, error)
	// Get current drivers for a list of trucks
	GetCurrentDriversByTruckIds(context.Context, *GetCurrentDriversByTruckIdsRequest) (*GetCurrentDriversByTruckIdsResponse, error)
	GetCurrentDriversByTrailerIds(context.Context, *GetCurrentDriversByTrailerIdsRequest) (*GetCurrentDriversByTrailerIdsResponse, error)
	mustEmbedUnimplementedTeamsServiceServer()
}

// UnimplementedTeamsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeamsServiceServer struct{}

func (UnimplementedTeamsServiceServer) GetDriverCrew(context.Context, *GetDriverCrewRequest) (*GetDriverCrewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverCrew not implemented")
}
func (UnimplementedTeamsServiceServer) GetDriverCrewWithDispatchers(context.Context, *GetDriverCrewRequest) (*GetDriverCrewWithDispatchersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverCrewWithDispatchers not implemented")
}
func (UnimplementedTeamsServiceServer) GetBusyVehicles(context.Context, *GetBusyVehiclesRequest) (*GetBusyVehiclesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBusyVehicles not implemented")
}
func (UnimplementedTeamsServiceServer) GetCurrentDriversByTruckIds(context.Context, *GetCurrentDriversByTruckIdsRequest) (*GetCurrentDriversByTruckIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentDriversByTruckIds not implemented")
}
func (UnimplementedTeamsServiceServer) GetCurrentDriversByTrailerIds(context.Context, *GetCurrentDriversByTrailerIdsRequest) (*GetCurrentDriversByTrailerIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentDriversByTrailerIds not implemented")
}
func (UnimplementedTeamsServiceServer) mustEmbedUnimplementedTeamsServiceServer() {}
func (UnimplementedTeamsServiceServer) testEmbeddedByValue()                      {}

// UnsafeTeamsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamsServiceServer will
// result in compilation errors.
type UnsafeTeamsServiceServer interface {
	mustEmbedUnimplementedTeamsServiceServer()
}

func RegisterTeamsServiceServer(s grpc.ServiceRegistrar, srv TeamsServiceServer) {
	// If the following call panics, it indicates UnimplementedTeamsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeamsService_ServiceDesc, srv)
}

func _TeamsService_GetDriverCrew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverCrewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServiceServer).GetDriverCrew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamsService_GetDriverCrew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServiceServer).GetDriverCrew(ctx, req.(*GetDriverCrewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamsService_GetDriverCrewWithDispatchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverCrewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServiceServer).GetDriverCrewWithDispatchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamsService_GetDriverCrewWithDispatchers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServiceServer).GetDriverCrewWithDispatchers(ctx, req.(*GetDriverCrewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamsService_GetBusyVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusyVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServiceServer).GetBusyVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamsService_GetBusyVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServiceServer).GetBusyVehicles(ctx, req.(*GetBusyVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamsService_GetCurrentDriversByTruckIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentDriversByTruckIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServiceServer).GetCurrentDriversByTruckIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamsService_GetCurrentDriversByTruckIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServiceServer).GetCurrentDriversByTruckIds(ctx, req.(*GetCurrentDriversByTruckIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamsService_GetCurrentDriversByTrailerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentDriversByTrailerIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamsServiceServer).GetCurrentDriversByTrailerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamsService_GetCurrentDriversByTrailerIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamsServiceServer).GetCurrentDriversByTrailerIds(ctx, req.(*GetCurrentDriversByTrailerIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeamsService_ServiceDesc is the grpc.ServiceDesc for TeamsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teams.TeamsService",
	HandlerType: (*TeamsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDriverCrew",
			Handler:    _TeamsService_GetDriverCrew_Handler,
		},
		{
			MethodName: "GetDriverCrewWithDispatchers",
			Handler:    _TeamsService_GetDriverCrewWithDispatchers_Handler,
		},
		{
			MethodName: "GetBusyVehicles",
			Handler:    _TeamsService_GetBusyVehicles_Handler,
		},
		{
			MethodName: "GetCurrentDriversByTruckIds",
			Handler:    _TeamsService_GetCurrentDriversByTruckIds_Handler,
		},
		{
			MethodName: "GetCurrentDriversByTrailerIds",
			Handler:    _TeamsService_GetCurrentDriversByTrailerIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teams/teams.proto",
}
