// pkg/proto/accounting/accounting.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: accounting/accounting.proto

package accounting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetKind names which kind of equipment carries the charge.
type AssetKind int32

const (
	AssetKind_ASSET_KIND_UNSPECIFIED AssetKind = 0
	AssetKind_ASSET_KIND_TRUCK       AssetKind = 1
	AssetKind_ASSET_KIND_TRAILER     AssetKind = 2
)

// Enum value maps for AssetKind.
var (
	AssetKind_name = map[int32]string{
		0: "ASSET_KIND_UNSPECIFIED",
		1: "ASSET_KIND_TRUCK",
		2: "ASSET_KIND_TRAILER",
	}
	AssetKind_value = map[string]int32{
		"ASSET_KIND_UNSPECIFIED": 0,
		"ASSET_KIND_TRUCK":       1,
		"ASSET_KIND_TRAILER":     2,
	}
)

func (x AssetKind) Enum() *AssetKind {
	p := new(AssetKind)
	*p = x
	return p
}

func (x AssetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_accounting_accounting_proto_enumTypes[0].Descriptor()
}

func (AssetKind) Type() protoreflect.EnumType {
	return &file_accounting_accounting_proto_enumTypes[0]
}

func (x AssetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetKind.Descriptor instead.
func (AssetKind) EnumDescriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{0}
}

// ChargeFault is accounting's PayEventFault, the same five words tasks uses for
// an incident resolution. It decides the payer.
type ChargeFault int32

const (
	ChargeFault_CHARGE_FAULT_UNSPECIFIED ChargeFault = 0
	ChargeFault_CHARGE_FAULT_EQUIPMENT   ChargeFault = 1
	ChargeFault_CHARGE_FAULT_DRIVER      ChargeFault = 2
	ChargeFault_CHARGE_FAULT_DISPATCHER  ChargeFault = 3
	ChargeFault_CHARGE_FAULT_CUSTOMER    ChargeFault = 4
	ChargeFault_CHARGE_FAULT_NONE        ChargeFault = 5
)

// Enum value maps for ChargeFault.
var (
	ChargeFault_name = map[int32]string{
		0: "CHARGE_FAULT_UNSPECIFIED",
		1: "CHARGE_FAULT_EQUIPMENT",
		2: "CHARGE_FAULT_DRIVER",
		3: "CHARGE_FAULT_DISPATCHER",
		4: "CHARGE_FAULT_CUSTOMER",
		5: "CHARGE_FAULT_NONE",
	}
	ChargeFault_value = map[string]int32{
		"CHARGE_FAULT_UNSPECIFIED": 0,
		"CHARGE_FAULT_EQUIPMENT":   1,
		"CHARGE_FAULT_DRIVER":      2,
		"CHARGE_FAULT_DISPATCHER":  3,
		"CHARGE_FAULT_CUSTOMER":    4,
		"CHARGE_FAULT_NONE":        5,
	}
)

func (x ChargeFault) Enum() *ChargeFault {
	p := new(ChargeFault)
	*p = x
	return p
}

func (x ChargeFault) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeFault) Descriptor() protoreflect.EnumDescriptor {
	return file_accounting_accounting_proto_enumTypes[1].Descriptor()
}

func (ChargeFault) Type() protoreflect.EnumType {
	return &file_accounting_accounting_proto_enumTypes[1]
}

func (x ChargeFault) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeFault.Descriptor instead.
func (ChargeFault) EnumDescriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{1}
}

// ChargeSourceKind records where a charge came from, so a row can always be
// walked back to the thing that caused it.
type ChargeSourceKind int32

const (
	ChargeSourceKind_CHARGE_SOURCE_KIND_UNSPECIFIED ChargeSourceKind = 0
	ChargeSourceKind_CHARGE_SOURCE_KIND_MANUAL      ChargeSourceKind = 1
	ChargeSourceKind_CHARGE_SOURCE_KIND_TASK        ChargeSourceKind = 2
	ChargeSourceKind_CHARGE_SOURCE_KIND_WORK_ORDER  ChargeSourceKind = 3
)

// Enum value maps for ChargeSourceKind.
var (
	ChargeSourceKind_name = map[int32]string{
		0: "CHARGE_SOURCE_KIND_UNSPECIFIED",
		1: "CHARGE_SOURCE_KIND_MANUAL",
		2: "CHARGE_SOURCE_KIND_TASK",
		3: "CHARGE_SOURCE_KIND_WORK_ORDER",
	}
	ChargeSourceKind_value = map[string]int32{
		"CHARGE_SOURCE_KIND_UNSPECIFIED": 0,
		"CHARGE_SOURCE_KIND_MANUAL":      1,
		"CHARGE_SOURCE_KIND_TASK":        2,
		"CHARGE_SOURCE_KIND_WORK_ORDER":  3,
	}
)

func (x ChargeSourceKind) Enum() *ChargeSourceKind {
	p := new(ChargeSourceKind)
	*p = x
	return p
}

func (x ChargeSourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeSourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_accounting_accounting_proto_enumTypes[2].Descriptor()
}

func (ChargeSourceKind) Type() protoreflect.EnumType {
	return &file_accounting_accounting_proto_enumTypes[2]
}

func (x ChargeSourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeSourceKind.Descriptor instead.
func (ChargeSourceKind) EnumDescriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{2}
}

type CreateAssetChargeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CompanyId string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ActorId   string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	AssetType AssetKind              `protobuf:"varint,3,opt,name=asset_type,json=assetType,proto3,enum=accounting.AssetKind" json:"asset_type,omitempty"`
	AssetId   string                 `protobuf:"bytes,4,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// The accounting type by CODE, not by id: the id is per-tenant and tasks has
	// no business knowing accounting's chart of accounts. A repair charge sends
	// "MAINTENANCE", which the seeded catalog already carries for every tenant.
	// An unknown code is refused rather than invented.
	TypeCode string `protobuf:"bytes,5,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	// Must be greater than zero. A work order that cost nothing (warranty) posts
	// no charge at all rather than a zero one.
	Amount float64 `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// The day the money belongs to — the service date, not the day the row was
	// written. It decides which driver held the asset and which pay period pays.
	ChargeDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=charge_date,json=chargeDate,proto3" json:"charge_date,omitempty"`
	Fault      ChargeFault            `protobuf:"varint,8,opt,name=fault,proto3,enum=accounting.ChargeFault" json:"fault,omitempty"`
	SourceKind ChargeSourceKind       `protobuf:"varint,9,opt,name=source_kind,json=sourceKind,proto3,enum=accounting.ChargeSourceKind" json:"source_kind,omitempty"`
	// The work order (or task) this came from. Required unless source_kind is
	// manual; it is how the charge is walked back and how the caller recognises
	// its own row.
	SourceId string `protobuf:"bytes,10,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Who was blamed, when accounting cannot work it out — that is fault
	// "dispatcher". For fault "driver" the holder on that day is the answer and
	// this is ignored.
	FaultPartyId  string `protobuf:"bytes,11,opt,name=fault_party_id,json=faultPartyId,proto3" json:"fault_party_id,omitempty"`
	Note          string `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetChargeRequest) Reset() {
	*x = CreateAssetChargeRequest{}
	mi := &file_accounting_accounting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetChargeRequest) ProtoMessage() {}

func (x *CreateAssetChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_accounting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetChargeRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetChargeRequest) Descriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAssetChargeRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CreateAssetChargeRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CreateAssetChargeRequest) GetAssetType() AssetKind {
	if x != nil {
		return x.AssetType
	}
	return AssetKind_ASSET_KIND_UNSPECIFIED
}

func (x *CreateAssetChargeRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateAssetChargeRequest) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *CreateAssetChargeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateAssetChargeRequest) GetChargeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChargeDate
	}
	return nil
}

func (x *CreateAssetChargeRequest) GetFault() ChargeFault {
	if x != nil {
		return x.Fault
	}
	return ChargeFault_CHARGE_FAULT_UNSPECIFIED
}

func (x *CreateAssetChargeRequest) GetSourceKind() ChargeSourceKind {
	if x != nil {
		return x.SourceKind
	}
	return ChargeSourceKind_CHARGE_SOURCE_KIND_UNSPECIFIED
}

func (x *CreateAssetChargeRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateAssetChargeRequest) GetFaultPartyId() string {
	if x != nil {
		return x.FaultPartyId
	}
	return ""
}

func (x *CreateAssetChargeRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateAssetChargeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created row. The caller stores it and treats its presence as "this work
	// order has been charged", which is what makes a retry safe.
	ChargeId string `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	// Where the row landed: "draft", "pending_ack", "posted" or "unrouted".
	// A driver-fault charge waits in pending_ack until somebody acknowledges it.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Set when the charge found nobody to bill and went to the unrouted queue —
	// no crew on the asset that day, or a dispatcher with no open statement. The
	// charge exists either way; this says a person has to route it.
	UnroutedReason string `protobuf:"bytes,3,opt,name=unrouted_reason,json=unroutedReason,proto3" json:"unrouted_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAssetChargeResponse) Reset() {
	*x = CreateAssetChargeResponse{}
	mi := &file_accounting_accounting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetChargeResponse) ProtoMessage() {}

func (x *CreateAssetChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_accounting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetChargeResponse.ProtoReflect.Descriptor instead.
func (*CreateAssetChargeResponse) Descriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAssetChargeResponse) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *CreateAssetChargeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAssetChargeResponse) GetUnroutedReason() string {
	if x != nil {
		return x.UnroutedReason
	}
	return ""
}

type ListTruckWeeklyPnLRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CompanyId string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// The window is [from, to): a statement belongs to it by the day its period
	// starts, a truck charge by its charge date.
	From *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Empty = every truck of the company.
	TruckIds      []string `protobuf:"bytes,4,rep,name=truck_ids,json=truckIds,proto3" json:"truck_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTruckWeeklyPnLRequest) Reset() {
	*x = ListTruckWeeklyPnLRequest{}
	mi := &file_accounting_accounting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTruckWeeklyPnLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTruckWeeklyPnLRequest) ProtoMessage() {}

func (x *ListTruckWeeklyPnLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_accounting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTruckWeeklyPnLRequest.ProtoReflect.Descriptor instead.
func (*ListTruckWeeklyPnLRequest) Descriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{2}
}

func (x *ListTruckWeeklyPnLRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListTruckWeeklyPnLRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListTruckWeeklyPnLRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListTruckWeeklyPnLRequest) GetTruckIds() []string {
	if x != nil {
		return x.TruckIds
	}
	return nil
}

// TruckWeekPnL is one truck's week: what it earned and where that went.
type TruckWeekPnL struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TruckId string                 `protobuf:"bytes,1,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	// Monday of the ISO week the row is bucketed on (date_trunc('week')). A
	// company whose week starts on another day should read its week as a
	// [from, to) window and add up the rows, not match on this label.
	WeekStart *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"`
	Revenue   float64                `protobuf:"fixed64,3,opt,name=revenue,proto3" json:"revenue,omitempty"`
	// What the company paid the drivers on this truck.
	DriverCost float64 `protobuf:"fixed64,4,opt,name=driver_cost,json=driverCost,proto3" json:"driver_cost,omitempty"`
	// What the owner was owed.
	OwnerPay float64 `protobuf:"fixed64,5,opt,name=owner_pay,json=ownerPay,proto3" json:"owner_pay,omitempty"`
	// Deductions taken on the owner's settlement for this truck.
	Deductions float64 `protobuf:"fixed64,6,opt,name=deductions,proto3" json:"deductions,omitempty"`
	// What the carrier itself paid for this truck (DEV-2241).
	AssetCosts float64 `protobuf:"fixed64,7,opt,name=asset_costs,json=assetCosts,proto3" json:"asset_costs,omitempty"`
	// revenue − driver_cost − owner_pay − asset_costs, derived by accounting so a
	// caller never carries the formula. Negative is a real answer.
	CompanyShare  float64 `protobuf:"fixed64,8,opt,name=company_share,json=companyShare,proto3" json:"company_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruckWeekPnL) Reset() {
	*x = TruckWeekPnL{}
	mi := &file_accounting_accounting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruckWeekPnL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckWeekPnL) ProtoMessage() {}

func (x *TruckWeekPnL) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_accounting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckWeekPnL.ProtoReflect.Descriptor instead.
func (*TruckWeekPnL) Descriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{3}
}

func (x *TruckWeekPnL) GetTruckId() string {
	if x != nil {
		return x.TruckId
	}
	return ""
}

func (x *TruckWeekPnL) GetWeekStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WeekStart
	}
	return nil
}

func (x *TruckWeekPnL) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *TruckWeekPnL) GetDriverCost() float64 {
	if x != nil {
		return x.DriverCost
	}
	return 0
}

func (x *TruckWeekPnL) GetOwnerPay() float64 {
	if x != nil {
		return x.OwnerPay
	}
	return 0
}

func (x *TruckWeekPnL) GetDeductions() float64 {
	if x != nil {
		return x.Deductions
	}
	return 0
}

func (x *TruckWeekPnL) GetAssetCosts() float64 {
	if x != nil {
		return x.AssetCosts
	}
	return 0
}

func (x *TruckWeekPnL) GetCompanyShare() float64 {
	if x != nil {
		return x.CompanyShare
	}
	return 0
}

type ListTruckWeeklyPnLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TruckWeekPnL        `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTruckWeeklyPnLResponse) Reset() {
	*x = ListTruckWeeklyPnLResponse{}
	mi := &file_accounting_accounting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTruckWeeklyPnLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTruckWeeklyPnLResponse) ProtoMessage() {}

func (x *ListTruckWeeklyPnLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_accounting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTruckWeeklyPnLResponse.ProtoReflect.Descriptor instead.
func (*ListTruckWeeklyPnLResponse) Descriptor() ([]byte, []int) {
	return file_accounting_accounting_proto_rawDescGZIP(), []int{4}
}

func (x *ListTruckWeeklyPnLResponse) GetRows() []*TruckWeekPnL {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_accounting_accounting_proto protoreflect.FileDescriptor

const file_accounting_accounting_proto_rawDesc = "" +
	"\n" +
	"\x1baccounting/accounting.proto\x12\n" +
	"accounting\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x03\n" +
	"\x18CreateAssetChargeRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x124\n" +
	"\n" +
	"asset_type\x18\x03 \x01(\x0e2\x15.accounting.AssetKindR\tassetType\x12\x19\n" +
	"\basset_id\x18\x04 \x01(\tR\aassetId\x12\x1b\n" +
	"\ttype_code\x18\x05 \x01(\tR\btypeCode\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12;\n" +
	"\vcharge_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"chargeDate\x12-\n" +
	"\x05fault\x18\b \x01(\x0e2\x17.accounting.ChargeFaultR\x05fault\x12=\n" +
	"\vsource_kind\x18\t \x01(\x0e2\x1c.accounting.ChargeSourceKindR\n" +
	"sourceKind\x12\x1b\n" +
	"\tsource_id\x18\n" +
	" \x01(\tR\bsourceId\x12$\n" +
	"\x0efault_party_id\x18\v \x01(\tR\ffaultPartyId\x12\x12\n" +
	"\x04note\x18\f \x01(\tR\x04note\"y\n" +
	"\x19CreateAssetChargeResponse\x12\x1b\n" +
	"\tcharge_id\x18\x01 \x01(\tR\bchargeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0funrouted_reason\x18\x03 \x01(\tR\x0eunroutedReason\"\xb3\x01\n" +
	"\x19ListTruckWeeklyPnLRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1b\n" +
	"\ttruck_ids\x18\x04 \x03(\tR\btruckIds\"\xa2\x02\n" +
	"\fTruckWeekPnL\x12\x19\n" +
	"\btruck_id\x18\x01 \x01(\tR\atruckId\x129\n" +
	"\n" +
	"week_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tweekStart\x12\x18\n" +
	"\arevenue\x18\x03 \x01(\x01R\arevenue\x12\x1f\n" +
	"\vdriver_cost\x18\x04 \x01(\x01R\n" +
	"driverCost\x12\x1b\n" +
	"\towner_pay\x18\x05 \x01(\x01R\bownerPay\x12\x1e\n" +
	"\n" +
	"deductions\x18\x06 \x01(\x01R\n" +
	"deductions\x12\x1f\n" +
	"\vasset_costs\x18\a \x01(\x01R\n" +
	"assetCosts\x12#\n" +
	"\rcompany_share\x18\b \x01(\x01R\fcompanyShare\"J\n" +
	"\x1aListTruckWeeklyPnLResponse\x12,\n" +
	"\x04rows\x18\x01 \x03(\v2\x18.accounting.TruckWeekPnLR\x04rows*U\n" +
	"\tAssetKind\x12\x1a\n" +
	"\x16ASSET_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ASSET_KIND_TRUCK\x10\x01\x12\x16\n" +
	"\x12ASSET_KIND_TRAILER\x10\x02*\xaf\x01\n" +
	"\vChargeFault\x12\x1c\n" +
	"\x18CHARGE_FAULT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CHARGE_FAULT_EQUIPMENT\x10\x01\x12\x17\n" +
	"\x13CHARGE_FAULT_DRIVER\x10\x02\x12\x1b\n" +
	"\x17CHARGE_FAULT_DISPATCHER\x10\x03\x12\x19\n" +
	"\x15CHARGE_FAULT_CUSTOMER\x10\x04\x12\x15\n" +
	"\x11CHARGE_FAULT_NONE\x10\x05*\x95\x01\n" +
	"\x10ChargeSourceKind\x12\"\n" +
	"\x1eCHARGE_SOURCE_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CHARGE_SOURCE_KIND_MANUAL\x10\x01\x12\x1b\n" +
	"\x17CHARGE_SOURCE_KIND_TASK\x10\x02\x12!\n" +
	"\x1dCHARGE_SOURCE_KIND_WORK_ORDER\x10\x032\xda\x01\n" +
	"\x11AccountingService\x12`\n" +
	"\x11CreateAssetCharge\x12$.accounting.CreateAssetChargeRequest\x1a%.accounting.CreateAssetChargeResponse\x12c\n" +
	"\x12ListTruckWeeklyPnL\x12%.accounting.ListTruckWeeklyPnLRequest\x1a&.accounting.ListTruckWeeklyPnLResponseB0Z.github.com/TMS360/backend-pkg/proto/accountingb\x06proto3"

var (
	file_accounting_accounting_proto_rawDescOnce sync.Once
	file_accounting_accounting_proto_rawDescData []byte
)

func file_accounting_accounting_proto_rawDescGZIP() []byte {
	file_accounting_accounting_proto_rawDescOnce.Do(func() {
		file_accounting_accounting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounting_accounting_proto_rawDesc), len(file_accounting_accounting_proto_rawDesc)))
	})
	return file_accounting_accounting_proto_rawDescData
}

var file_accounting_accounting_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_accounting_accounting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_accounting_accounting_proto_goTypes = []any{
	(AssetKind)(0),                     // 0: accounting.AssetKind
	(ChargeFault)(0),                   // 1: accounting.ChargeFault
	(ChargeSourceKind)(0),              // 2: accounting.ChargeSourceKind
	(*CreateAssetChargeRequest)(nil),   // 3: accounting.CreateAssetChargeRequest
	(*CreateAssetChargeResponse)(nil),  // 4: accounting.CreateAssetChargeResponse
	(*ListTruckWeeklyPnLRequest)(nil),  // 5: accounting.ListTruckWeeklyPnLRequest
	(*TruckWeekPnL)(nil),               // 6: accounting.TruckWeekPnL
	(*ListTruckWeeklyPnLResponse)(nil), // 7: accounting.ListTruckWeeklyPnLResponse
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_accounting_accounting_proto_depIdxs = []int32{
	0,  // 0: accounting.CreateAssetChargeRequest.asset_type:type_name -> accounting.AssetKind
	8,  // 1: accounting.CreateAssetChargeRequest.charge_date:type_name -> google.protobuf.Timestamp
	1,  // 2: accounting.CreateAssetChargeRequest.fault:type_name -> accounting.ChargeFault
	2,  // 3: accounting.CreateAssetChargeRequest.source_kind:type_name -> accounting.ChargeSourceKind
	8,  // 4: accounting.ListTruckWeeklyPnLRequest.from:type_name -> google.protobuf.Timestamp
	8,  // 5: accounting.ListTruckWeeklyPnLRequest.to:type_name -> google.protobuf.Timestamp
	8,  // 6: accounting.TruckWeekPnL.week_start:type_name -> google.protobuf.Timestamp
	6,  // 7: accounting.ListTruckWeeklyPnLResponse.rows:type_name -> accounting.TruckWeekPnL
	3,  // 8: accounting.AccountingService.CreateAssetCharge:input_type -> accounting.CreateAssetChargeRequest
	5,  // 9: accounting.AccountingService.ListTruckWeeklyPnL:input_type -> accounting.ListTruckWeeklyPnLRequest
	4,  // 10: accounting.AccountingService.CreateAssetCharge:output_type -> accounting.CreateAssetChargeResponse
	7,  // 11: accounting.AccountingService.ListTruckWeeklyPnL:output_type -> accounting.ListTruckWeeklyPnLResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_accounting_accounting_proto_init() }
func file_accounting_accounting_proto_init() {
	if File_accounting_accounting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounting_accounting_proto_rawDesc), len(file_accounting_accounting_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounting_accounting_proto_goTypes,
		DependencyIndexes: file_accounting_accounting_proto_depIdxs,
		EnumInfos:         file_accounting_accounting_proto_enumTypes,
		MessageInfos:      file_accounting_accounting_proto_msgTypes,
	}.Build()
	File_accounting_accounting_proto = out.File
	file_accounting_accounting_proto_goTypes = nil
	file_accounting_accounting_proto_depIdxs = nil
}
