// pkg/proto/accounting/accounting.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: accounting/accounting.proto

package accounting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountingService_CreateAssetCharge_FullMethodName = "/accounting.AccountingService/CreateAssetCharge"
)

// AccountingServiceClient is the client API for AccountingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountingService is backend-accounting's internal API.
//
// It exists because money has no other door: createAssetCharge and its siblings
// are GraphQL mutations meant for a person, and there is no GraphQL client
// between services in this fleet. The first caller is the maintenance work
// order (backend-tasks, DEV-2252), which owes a repair charge the moment it
// closes.
//
// PERMISSIONS ARE CHECKED BY THE CALLER, the same contract backend-load's gRPC
// server carries: these calls arrive with an internal token rather than a user
// JWT, so company_id and actor_id are passed explicitly and the calling service
// has already gated the user action that led here.
type AccountingServiceClient interface {
	// Charge a truck or a trailer once — a repair bill, a tyre, a mirror.
	//
	// Where the money goes is decided by the FAULT, not by the caller: fault
	// "driver" reaches the holder on that day and waits to be acknowledged,
	// "dispatcher" reaches the named dispatcher, and the other three reach the
	// company and the truck's P&L. Nobody to bill is never silently the company —
	// it goes to the unrouted queue with a reason.
	//
	// NOT IDEMPOTENT. Accounting deliberately allows two identical charges (two
	// tyres on one day is a real thing), so calling this twice posts twice. The
	// caller owns the key: backend-tasks stores the returned charge_id on the
	// work order and never calls again once it has one.
	CreateAssetCharge(ctx context.Context, in *CreateAssetChargeRequest, opts ...grpc.CallOption) (*CreateAssetChargeResponse, error)
}

type accountingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountingServiceClient(cc grpc.ClientConnInterface) AccountingServiceClient {
	return &accountingServiceClient{cc}
}

func (c *accountingServiceClient) CreateAssetCharge(ctx context.Context, in *CreateAssetChargeRequest, opts ...grpc.CallOption) (*CreateAssetChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssetChargeResponse)
	err := c.cc.Invoke(ctx, AccountingService_CreateAssetCharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountingServiceServer is the server API for AccountingService service.
// All implementations must embed UnimplementedAccountingServiceServer
// for forward compatibility.
//
// AccountingService is backend-accounting's internal API.
//
// It exists because money has no other door: createAssetCharge and its siblings
// are GraphQL mutations meant for a person, and there is no GraphQL client
// between services in this fleet. The first caller is the maintenance work
// order (backend-tasks, DEV-2252), which owes a repair charge the moment it
// closes.
//
// PERMISSIONS ARE CHECKED BY THE CALLER, the same contract backend-load's gRPC
// server carries: these calls arrive with an internal token rather than a user
// JWT, so company_id and actor_id are passed explicitly and the calling service
// has already gated the user action that led here.
type AccountingServiceServer interface {
	// Charge a truck or a trailer once — a repair bill, a tyre, a mirror.
	//
	// Where the money goes is decided by the FAULT, not by the caller: fault
	// "driver" reaches the holder on that day and waits to be acknowledged,
	// "dispatcher" reaches the named dispatcher, and the other three reach the
	// company and the truck's P&L. Nobody to bill is never silently the company —
	// it goes to the unrouted queue with a reason.
	//
	// NOT IDEMPOTENT. Accounting deliberately allows two identical charges (two
	// tyres on one day is a real thing), so calling this twice posts twice. The
	// caller owns the key: backend-tasks stores the returned charge_id on the
	// work order and never calls again once it has one.
	CreateAssetCharge(context.Context, *CreateAssetChargeRequest) (*CreateAssetChargeResponse, error)
	mustEmbedUnimplementedAccountingServiceServer()
}

// UnimplementedAccountingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountingServiceServer struct{}

func (UnimplementedAccountingServiceServer) CreateAssetCharge(context.Context, *CreateAssetChargeRequest) (*CreateAssetChargeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssetCharge not implemented")
}
func (UnimplementedAccountingServiceServer) mustEmbedUnimplementedAccountingServiceServer() {}
func (UnimplementedAccountingServiceServer) testEmbeddedByValue()                           {}

// UnsafeAccountingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountingServiceServer will
// result in compilation errors.
type UnsafeAccountingServiceServer interface {
	mustEmbedUnimplementedAccountingServiceServer()
}

func RegisterAccountingServiceServer(s grpc.ServiceRegistrar, srv AccountingServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountingService_ServiceDesc, srv)
}

func _AccountingService_CreateAssetCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountingServiceServer).CreateAssetCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountingService_CreateAssetCharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountingServiceServer).CreateAssetCharge(ctx, req.(*CreateAssetChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountingService_ServiceDesc is the grpc.ServiceDesc for AccountingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accounting.AccountingService",
	HandlerType: (*AccountingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssetCharge",
			Handler:    _AccountingService_CreateAssetCharge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounting/accounting.proto",
}
